// ──────────────────────────────────────────────────────────────
// ███████╗██╗   ██╗███╗   ██╗██╗  ██╗ █████╗ ██╗
// ██╔════╝██║   ██║████╗  ██║██║ ██╔╝██╔══██╗██║
// █████╗  ██║   ██║██╔██╗ ██║█████╔╝ ███████║██║
// ██╔══╝  ██║   ██║██║╚██╗██║██╔═██╗ ██╔══██║██║
// ██║     ╚██████╔╝██║ ╚████║██║  ██╗██║  ██║██║
// ╚═╝      ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝
//
// AUTO-GENERATED — DO NOT EDIT
// Source: https://models.dev
// Update: pnpm --filter=@funkai/models generate:models
// ──────────────────────────────────────────────────────────────

import type { ModelDefinition } from '../types.js'

export const ALIBABA_MODELS = [
  { id: 'qwen-vl-plus', name: 'Qwen-VL Plus', provider: 'alibaba', family: 'qwen', pricing: { input: 2.1e-7, output: 6.3e-7 }, contextWindow: 131072, maxOutput: 8192, modalities: { input: ["text","image"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen-vl-max', name: 'Qwen-VL Max', provider: 'alibaba', family: 'qwen', pricing: { input: 8.000000000000001e-7, output: 0.0000032000000000000003 }, contextWindow: 131072, maxOutput: 8192, modalities: { input: ["text","image"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen3-next-80b-a3b-thinking', name: 'Qwen3-Next 80B-A3B (Thinking)', provider: 'alibaba', family: 'qwen', pricing: { input: 5e-7, output: 0.000006 }, contextWindow: 131072, maxOutput: 32768, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen3-coder-480b-a35b-instruct', name: 'Qwen3-Coder 480B-A35B Instruct', provider: 'alibaba', family: 'qwen', pricing: { input: 0.0000015, output: 0.0000075 }, contextWindow: 262144, maxOutput: 65536, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen3-14b', name: 'Qwen3 14B', provider: 'alibaba', family: 'qwen', pricing: { input: 3.5e-7, output: 0.0000014 }, contextWindow: 131072, maxOutput: 8192, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen3-coder-flash', name: 'Qwen3 Coder Flash', provider: 'alibaba', family: 'qwen', pricing: { input: 3e-7, output: 0.0000015 }, contextWindow: 1000000, maxOutput: 65536, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen3-vl-30b-a3b', name: 'Qwen3-VL 30B-A3B', provider: 'alibaba', family: 'qwen', pricing: { input: 2.0000000000000002e-7, output: 8.000000000000001e-7 }, contextWindow: 131072, maxOutput: 32768, modalities: { input: ["text","image"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen3-asr-flash', name: 'Qwen3-ASR Flash', provider: 'alibaba', family: 'qwen', pricing: { input: 3.5e-8, output: 3.5e-8 }, contextWindow: 53248, maxOutput: 4096, modalities: { input: ["audio"], output: ["text"] }, capabilities: { reasoning: false, toolCall: false, attachment: false, structuredOutput: false } },
  { id: 'qwen-max', name: 'Qwen Max', provider: 'alibaba', family: 'qwen', pricing: { input: 0.0000016000000000000001, output: 0.0000064000000000000006 }, contextWindow: 32768, maxOutput: 8192, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen-turbo', name: 'Qwen Turbo', provider: 'alibaba', family: 'qwen', pricing: { input: 5.0000000000000004e-8, output: 2.0000000000000002e-7 }, contextWindow: 1000000, maxOutput: 16384, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen2-5-7b-instruct', name: 'Qwen2.5 7B Instruct', provider: 'alibaba', family: 'qwen', pricing: { input: 1.75e-7, output: 7e-7 }, contextWindow: 131072, maxOutput: 8192, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen2-5-vl-72b-instruct', name: 'Qwen2.5-VL 72B Instruct', provider: 'alibaba', family: 'qwen', pricing: { input: 0.0000028, output: 0.000008400000000000001 }, contextWindow: 131072, maxOutput: 8192, modalities: { input: ["text","image"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen2-5-14b-instruct', name: 'Qwen2.5 14B Instruct', provider: 'alibaba', family: 'qwen', pricing: { input: 3.5e-7, output: 0.0000014 }, contextWindow: 131072, maxOutput: 8192, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen3-8b', name: 'Qwen3 8B', provider: 'alibaba', family: 'qwen', pricing: { input: 1.8e-7, output: 7e-7 }, contextWindow: 131072, maxOutput: 8192, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen3-32b', name: 'Qwen3 32B', provider: 'alibaba', family: 'qwen', pricing: { input: 7e-7, output: 0.0000028 }, contextWindow: 131072, maxOutput: 16384, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen3.5-397b-a17b', name: 'Qwen3.5 397B-A17B', provider: 'alibaba', family: 'qwen', pricing: { input: 6e-7, output: 0.0000036000000000000003 }, contextWindow: 262144, maxOutput: 65536, modalities: { input: ["text","image","video"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qvq-max', name: 'QVQ Max', provider: 'alibaba', family: 'qvq', pricing: { input: 0.0000012, output: 0.0000048 }, contextWindow: 131072, maxOutput: 8192, modalities: { input: ["text","image"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen2-5-omni-7b', name: 'Qwen2.5-Omni 7B', provider: 'alibaba', family: 'qwen', pricing: { input: 1.0000000000000001e-7, output: 4.0000000000000003e-7 }, contextWindow: 32768, maxOutput: 2048, modalities: { input: ["text","image","audio","video"], output: ["text","audio"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen2-5-vl-7b-instruct', name: 'Qwen2.5-VL 7B Instruct', provider: 'alibaba', family: 'qwen', pricing: { input: 3.5e-7, output: 0.0000010500000000000001 }, contextWindow: 131072, maxOutput: 8192, modalities: { input: ["text","image"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen-omni-turbo-realtime', name: 'Qwen-Omni Turbo Realtime', provider: 'alibaba', family: 'qwen', pricing: { input: 2.7e-7, output: 0.0000010700000000000001 }, contextWindow: 32768, maxOutput: 2048, modalities: { input: ["text","image","audio"], output: ["text","audio"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen3-235b-a22b', name: 'Qwen3 235B-A22B', provider: 'alibaba', family: 'qwen', pricing: { input: 7e-7, output: 0.0000028 }, contextWindow: 131072, maxOutput: 16384, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen3-coder-30b-a3b-instruct', name: 'Qwen3-Coder 30B-A3B Instruct', provider: 'alibaba', family: 'qwen', pricing: { input: 4.5000000000000003e-7, output: 0.00000225 }, contextWindow: 262144, maxOutput: 65536, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen-omni-turbo', name: 'Qwen-Omni Turbo', provider: 'alibaba', family: 'qwen', pricing: { input: 7e-8, output: 2.7e-7 }, contextWindow: 32768, maxOutput: 2048, modalities: { input: ["text","image","audio","video"], output: ["text","audio"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen-mt-plus', name: 'Qwen-MT Plus', provider: 'alibaba', family: 'qwen', pricing: { input: 0.00000246, output: 0.00000737 }, contextWindow: 16384, maxOutput: 8192, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: false, attachment: false, structuredOutput: false } },
  { id: 'qwen3-vl-plus', name: 'Qwen3-VL Plus', provider: 'alibaba', family: 'qwen', pricing: { input: 2.0000000000000002e-7, output: 0.0000016000000000000001 }, contextWindow: 262144, maxOutput: 32768, modalities: { input: ["text","image"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen3-livetranslate-flash-realtime', name: 'Qwen3-LiveTranslate Flash Realtime', provider: 'alibaba', family: 'qwen', pricing: { input: 0.00001, output: 0.00001 }, contextWindow: 53248, maxOutput: 4096, modalities: { input: ["text","image","audio","video"], output: ["text","audio"] }, capabilities: { reasoning: false, toolCall: false, attachment: false, structuredOutput: false } },
  { id: 'qwen-plus', name: 'Qwen Plus', provider: 'alibaba', family: 'qwen', pricing: { input: 4.0000000000000003e-7, output: 0.0000012 }, contextWindow: 1000000, maxOutput: 32768, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen2-5-32b-instruct', name: 'Qwen2.5 32B Instruct', provider: 'alibaba', family: 'qwen', pricing: { input: 7e-7, output: 0.0000028 }, contextWindow: 131072, maxOutput: 8192, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen3-next-80b-a3b-instruct', name: 'Qwen3-Next 80B-A3B Instruct', provider: 'alibaba', family: 'qwen', pricing: { input: 5e-7, output: 0.000002 }, contextWindow: 131072, maxOutput: 32768, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen3.5-plus', name: 'Qwen3.5 Plus', provider: 'alibaba', family: 'qwen', pricing: { input: 4.0000000000000003e-7, output: 0.0000024 }, contextWindow: 1000000, maxOutput: 65536, modalities: { input: ["text","image","video"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen3-max', name: 'Qwen3 Max', provider: 'alibaba', family: 'qwen', pricing: { input: 0.0000012, output: 0.000006 }, contextWindow: 262144, maxOutput: 65536, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen3-omni-flash', name: 'Qwen3-Omni Flash', provider: 'alibaba', family: 'qwen', pricing: { input: 4.3e-7, output: 0.00000166 }, contextWindow: 65536, maxOutput: 16384, modalities: { input: ["text","image","audio","video"], output: ["text","audio"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen3-coder-plus', name: 'Qwen3 Coder Plus', provider: 'alibaba', family: 'qwen', pricing: { input: 0.000001, output: 0.000005 }, contextWindow: 1048576, maxOutput: 65536, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen-flash', name: 'Qwen Flash', provider: 'alibaba', family: 'qwen', pricing: { input: 5.0000000000000004e-8, output: 4.0000000000000003e-7 }, contextWindow: 1000000, maxOutput: 32768, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen2-5-72b-instruct', name: 'Qwen2.5 72B Instruct', provider: 'alibaba', family: 'qwen', pricing: { input: 0.0000014, output: 0.0000056 }, contextWindow: 131072, maxOutput: 8192, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen3-omni-flash-realtime', name: 'Qwen3-Omni Flash Realtime', provider: 'alibaba', family: 'qwen', pricing: { input: 5.2e-7, output: 0.00000199 }, contextWindow: 65536, maxOutput: 16384, modalities: { input: ["text","image","audio","video"], output: ["text","audio"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen-vl-ocr', name: 'Qwen-VL OCR', provider: 'alibaba', family: 'qwen', pricing: { input: 7.2e-7, output: 7.2e-7 }, contextWindow: 34096, maxOutput: 4096, modalities: { input: ["text","image"], output: ["text"] }, capabilities: { reasoning: false, toolCall: false, attachment: false, structuredOutput: false } },
  { id: 'qwq-plus', name: 'QwQ Plus', provider: 'alibaba', family: 'qwen', pricing: { input: 8.000000000000001e-7, output: 0.0000024 }, contextWindow: 131072, maxOutput: 8192, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen3-vl-235b-a22b', name: 'Qwen3-VL 235B-A22B', provider: 'alibaba', family: 'qwen', pricing: { input: 7e-7, output: 0.0000028 }, contextWindow: 131072, maxOutput: 32768, modalities: { input: ["text","image"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen-plus-character-ja', name: 'Qwen Plus Character (Japanese)', provider: 'alibaba', family: 'qwen', pricing: { input: 5e-7, output: 0.0000014 }, contextWindow: 8192, maxOutput: 512, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen-mt-turbo', name: 'Qwen-MT Turbo', provider: 'alibaba', family: 'qwen', pricing: { input: 1.6e-7, output: 4.9e-7 }, contextWindow: 16384, maxOutput: 8192, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: false, attachment: false, structuredOutput: false } },
] as const satisfies readonly ModelDefinition[]
