// ──────────────────────────────────────────────────────────────
// ███████╗██╗   ██╗███╗   ██╗██╗  ██╗ █████╗ ██╗
// ██╔════╝██║   ██║████╗  ██║██║ ██╔╝██╔══██╗██║
// █████╗  ██║   ██║██╔██╗ ██║█████╔╝ ███████║██║
// ██╔══╝  ██║   ██║██║╚██╗██║██╔═██╗ ██╔══██║██║
// ██║     ╚██████╔╝██║ ╚████║██║  ██╗██║  ██║██║
// ╚═╝      ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝
//
// AUTO-GENERATED — DO NOT EDIT
// Source: https://models.dev
// Update: pnpm --filter=@funkai/models generate:models
// ──────────────────────────────────────────────────────────────

import type { ModelDefinition } from "../types.js";

export const ALIBABA_MODELS = [
  {
    id: "qwen-vl-plus",
    name: "Qwen-VL Plus",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 2.1e-7, output: 6.3e-7 },
    contextWindow: 131_072,
    maxOutput: 8192,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen-vl-max",
    name: "Qwen-VL Max",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 8e-7, output: 0.000_003_2 },
    contextWindow: 131_072,
    maxOutput: 8192,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen3-next-80b-a3b-thinking",
    name: "Qwen3-Next 80B-A3B (Thinking)",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 5e-7, output: 0.000_006 },
    contextWindow: 131_072,
    maxOutput: 32_768,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen3-coder-480b-a35b-instruct",
    name: "Qwen3-Coder 480B-A35B Instruct",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 0.000_001_5, output: 0.000_007_5 },
    contextWindow: 262_144,
    maxOutput: 65_536,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen3-14b",
    name: "Qwen3 14B",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 3.5e-7, output: 0.000_001_4, reasoning: 0.000_004_2 },
    contextWindow: 131_072,
    maxOutput: 8192,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen3-coder-flash",
    name: "Qwen3 Coder Flash",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 3e-7, output: 0.000_001_5 },
    contextWindow: 1_000_000,
    maxOutput: 65_536,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen3-vl-30b-a3b",
    name: "Qwen3-VL 30B-A3B",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 2e-7, output: 8e-7, reasoning: 0.000_002_4 },
    contextWindow: 131_072,
    maxOutput: 32_768,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen3-asr-flash",
    name: "Qwen3-ASR Flash",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 3.5e-8, output: 3.5e-8 },
    contextWindow: 53_248,
    maxOutput: 4096,
    modalities: { input: ["audio"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: false, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen-max",
    name: "Qwen Max",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 0.000_001_6, output: 0.000_006_4 },
    contextWindow: 32_768,
    maxOutput: 8192,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen-turbo",
    name: "Qwen Turbo",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 5e-8, output: 2e-7, reasoning: 5e-7 },
    contextWindow: 1_000_000,
    maxOutput: 16_384,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen2-5-7b-instruct",
    name: "Qwen2.5 7B Instruct",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 1.75e-7, output: 7e-7 },
    contextWindow: 131_072,
    maxOutput: 8192,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen2-5-vl-72b-instruct",
    name: "Qwen2.5-VL 72B Instruct",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 0.000_002_8, output: 0.000_008_4 },
    contextWindow: 131_072,
    maxOutput: 8192,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen2-5-14b-instruct",
    name: "Qwen2.5 14B Instruct",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 3.5e-7, output: 0.000_001_4 },
    contextWindow: 131_072,
    maxOutput: 8192,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen3-8b",
    name: "Qwen3 8B",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 1.8e-7, output: 7e-7, reasoning: 0.000_002_1 },
    contextWindow: 131_072,
    maxOutput: 8192,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen3-32b",
    name: "Qwen3 32B",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 7e-7, output: 0.000_002_8, reasoning: 0.000_008_4 },
    contextWindow: 131_072,
    maxOutput: 16_384,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen3.5-397b-a17b",
    name: "Qwen3.5 397B-A17B",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 6e-7, output: 0.000_003_6, reasoning: 0.000_003_6 },
    contextWindow: 262_144,
    maxOutput: 65_536,
    modalities: { input: ["text", "image", "video"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qvq-max",
    name: "QVQ Max",
    provider: "alibaba",
    family: "qvq",
    pricing: { input: 0.000_001_2, output: 0.000_004_8 },
    contextWindow: 131_072,
    maxOutput: 8192,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen2-5-omni-7b",
    name: "Qwen2.5-Omni 7B",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 1e-7, output: 4e-7 },
    contextWindow: 32_768,
    maxOutput: 2048,
    modalities: { input: ["text", "image", "audio", "video"], output: ["text", "audio"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen2-5-vl-7b-instruct",
    name: "Qwen2.5-VL 7B Instruct",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 3.5e-7, output: 0.000_001_05 },
    contextWindow: 131_072,
    maxOutput: 8192,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen-omni-turbo-realtime",
    name: "Qwen-Omni Turbo Realtime",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 2.7e-7, output: 0.000_001_07 },
    contextWindow: 32_768,
    maxOutput: 2048,
    modalities: { input: ["text", "image", "audio"], output: ["text", "audio"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen3-235b-a22b",
    name: "Qwen3 235B-A22B",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 7e-7, output: 0.000_002_8, reasoning: 0.000_008_4 },
    contextWindow: 131_072,
    maxOutput: 16_384,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen3-coder-30b-a3b-instruct",
    name: "Qwen3-Coder 30B-A3B Instruct",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 4.5e-7, output: 0.000_002_25 },
    contextWindow: 262_144,
    maxOutput: 65_536,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen-omni-turbo",
    name: "Qwen-Omni Turbo",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 7e-8, output: 2.7e-7 },
    contextWindow: 32_768,
    maxOutput: 2048,
    modalities: { input: ["text", "image", "audio", "video"], output: ["text", "audio"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen-mt-plus",
    name: "Qwen-MT Plus",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 0.000_002_46, output: 0.000_007_37 },
    contextWindow: 16_384,
    maxOutput: 8192,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: false, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen3-vl-plus",
    name: "Qwen3-VL Plus",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 2e-7, output: 0.000_001_6, reasoning: 0.000_004_8 },
    contextWindow: 262_144,
    maxOutput: 32_768,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen3-livetranslate-flash-realtime",
    name: "Qwen3-LiveTranslate Flash Realtime",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 0.000_01, output: 0.000_01 },
    contextWindow: 53_248,
    maxOutput: 4096,
    modalities: { input: ["text", "image", "audio", "video"], output: ["text", "audio"] },
    capabilities: { reasoning: false, toolCall: false, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen-plus",
    name: "Qwen Plus",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 4e-7, output: 0.000_001_2, reasoning: 0.000_004 },
    contextWindow: 1_000_000,
    maxOutput: 32_768,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen2-5-32b-instruct",
    name: "Qwen2.5 32B Instruct",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 7e-7, output: 0.000_002_8 },
    contextWindow: 131_072,
    maxOutput: 8192,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen3-next-80b-a3b-instruct",
    name: "Qwen3-Next 80B-A3B Instruct",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 5e-7, output: 0.000_002 },
    contextWindow: 131_072,
    maxOutput: 32_768,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen3.5-plus",
    name: "Qwen3.5 Plus",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 4e-7, output: 0.000_002_4, reasoning: 0.000_002_4 },
    contextWindow: 1_000_000,
    maxOutput: 65_536,
    modalities: { input: ["text", "image", "video"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen3-max",
    name: "Qwen3 Max",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 0.000_001_2, output: 0.000_006 },
    contextWindow: 262_144,
    maxOutput: 65_536,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen3-omni-flash",
    name: "Qwen3-Omni Flash",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 4.3e-7, output: 0.000_001_66 },
    contextWindow: 65_536,
    maxOutput: 16_384,
    modalities: { input: ["text", "image", "audio", "video"], output: ["text", "audio"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen3-coder-plus",
    name: "Qwen3 Coder Plus",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 0.000_001, output: 0.000_005 },
    contextWindow: 1_048_576,
    maxOutput: 65_536,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen-flash",
    name: "Qwen Flash",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 5e-8, output: 4e-7 },
    contextWindow: 1_000_000,
    maxOutput: 32_768,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen2-5-72b-instruct",
    name: "Qwen2.5 72B Instruct",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 0.000_001_4, output: 0.000_005_6 },
    contextWindow: 131_072,
    maxOutput: 8192,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen3-omni-flash-realtime",
    name: "Qwen3-Omni Flash Realtime",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 5.2e-7, output: 0.000_001_99 },
    contextWindow: 65_536,
    maxOutput: 16_384,
    modalities: { input: ["text", "image", "audio", "video"], output: ["text", "audio"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen-vl-ocr",
    name: "Qwen-VL OCR",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 7.2e-7, output: 7.2e-7 },
    contextWindow: 34_096,
    maxOutput: 4096,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: false, attachment: false, structuredOutput: false },
  },
  {
    id: "qwq-plus",
    name: "QwQ Plus",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 8e-7, output: 0.000_002_4 },
    contextWindow: 131_072,
    maxOutput: 8192,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen3-vl-235b-a22b",
    name: "Qwen3-VL 235B-A22B",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 7e-7, output: 0.000_002_8, reasoning: 0.000_008_4 },
    contextWindow: 131_072,
    maxOutput: 32_768,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen-plus-character-ja",
    name: "Qwen Plus Character (Japanese)",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 5e-7, output: 0.000_001_4 },
    contextWindow: 8192,
    maxOutput: 512,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen-mt-turbo",
    name: "Qwen-MT Turbo",
    provider: "alibaba",
    family: "qwen",
    pricing: { input: 1.6e-7, output: 4.9e-7 },
    contextWindow: 16_384,
    maxOutput: 8192,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: false, attachment: false, structuredOutput: false },
  },
] as const satisfies readonly ModelDefinition[];
