// ──────────────────────────────────────────────────────────────
// ███████╗██╗   ██╗███╗   ██╗██╗  ██╗ █████╗ ██╗
// ██╔════╝██║   ██║████╗  ██║██║ ██╔╝██╔══██╗██║
// █████╗  ██║   ██║██╔██╗ ██║█████╔╝ ███████║██║
// ██╔══╝  ██║   ██║██║╚██╗██║██╔═██╗ ██╔══██║██║
// ██║     ╚██████╔╝██║ ╚████║██║  ██╗██║  ██║██║
// ╚═╝      ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝
//
// AUTO-GENERATED — DO NOT EDIT
// Source: https://models.dev
// Update: pnpm --filter=@funkai/models generate:models
// ──────────────────────────────────────────────────────────────

import type { ModelDefinition } from "../types.js";

export const AMAZON_BEDROCK_MODELS = [
  {
    id: "deepseek.r1-v1:0",
    name: "DeepSeek-R1",
    provider: "amazon-bedrock",
    family: "deepseek-thinking",
    pricing: { input: 0.000_001_35, output: 0.000_005_4 },
    contextWindow: 128_000,
    maxOutput: 32_768,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "meta.llama3-1-70b-instruct-v1:0",
    name: "Llama 3.1 70B Instruct",
    provider: "amazon-bedrock",
    family: "llama",
    pricing: { input: 7.2e-7, output: 7.2e-7 },
    contextWindow: 128_000,
    maxOutput: 4096,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen.qwen3-coder-480b-a35b-v1:0",
    name: "Qwen3 Coder 480B A35B Instruct",
    provider: "amazon-bedrock",
    family: "qwen",
    pricing: { input: 2.2e-7, output: 0.000_001_8 },
    contextWindow: 131_072,
    maxOutput: 65_536,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "eu.anthropic.claude-sonnet-4-6",
    name: "Claude Sonnet 4.6 (EU)",
    provider: "amazon-bedrock",
    family: "claude-sonnet",
    pricing: { input: 0.000_003, output: 0.000_015, cacheRead: 3e-7, cacheWrite: 0.000_003_75 },
    contextWindow: 200_000,
    maxOutput: 64_000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "eu.anthropic.claude-haiku-4-5-20251001-v1:0",
    name: "Claude Haiku 4.5 (EU)",
    provider: "amazon-bedrock",
    family: "claude-haiku",
    pricing: { input: 0.000_001, output: 0.000_005, cacheRead: 1e-7, cacheWrite: 0.000_001_25 },
    contextWindow: 200_000,
    maxOutput: 64_000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "mistral.mistral-large-3-675b-instruct",
    name: "Mistral Large 3",
    provider: "amazon-bedrock",
    family: "mistral",
    pricing: { input: 5e-7, output: 0.000_001_5 },
    contextWindow: 256_000,
    maxOutput: 8192,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "openai.gpt-oss-120b-1:0",
    name: "gpt-oss-120b",
    provider: "amazon-bedrock",
    family: "gpt-oss",
    pricing: { input: 1.5e-7, output: 6e-7 },
    contextWindow: 128_000,
    maxOutput: 4096,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "us.anthropic.claude-opus-4-20250514-v1:0",
    name: "Claude Opus 4 (US)",
    provider: "amazon-bedrock",
    family: "claude-opus",
    pricing: { input: 0.000_015, output: 0.000_075, cacheRead: 0.000_001_5, cacheWrite: 0.000_018_75 },
    contextWindow: 200_000,
    maxOutput: 32_000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "nvidia.nemotron-nano-12b-v2",
    name: "NVIDIA Nemotron Nano 12B v2 VL BF16",
    provider: "amazon-bedrock",
    family: "nemotron",
    pricing: { input: 2e-7, output: 6e-7 },
    contextWindow: 128_000,
    maxOutput: 4096,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "anthropic.claude-3-7-sonnet-20250219-v1:0",
    name: "Claude Sonnet 3.7",
    provider: "amazon-bedrock",
    family: "claude-sonnet",
    pricing: { input: 0.000_003, output: 0.000_015, cacheRead: 3e-7, cacheWrite: 0.000_003_75 },
    contextWindow: 200_000,
    maxOutput: 8192,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "anthropic.claude-sonnet-4-6",
    name: "Claude Sonnet 4.6",
    provider: "amazon-bedrock",
    family: "claude-sonnet",
    pricing: { input: 0.000_003, output: 0.000_015, cacheRead: 3e-7, cacheWrite: 0.000_003_75 },
    contextWindow: 200_000,
    maxOutput: 64_000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "minimax.minimax-m2.1",
    name: "MiniMax M2.1",
    provider: "amazon-bedrock",
    family: "minimax",
    pricing: { input: 3e-7, output: 0.000_001_2 },
    contextWindow: 204_800,
    maxOutput: 131_072,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "global.anthropic.claude-opus-4-5-20251101-v1:0",
    name: "Claude Opus 4.5 (Global)",
    provider: "amazon-bedrock",
    family: "claude-opus",
    pricing: { input: 0.000_005, output: 0.000_025, cacheRead: 5e-7, cacheWrite: 0.000_006_25 },
    contextWindow: 200_000,
    maxOutput: 64_000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "mistral.ministral-3-8b-instruct",
    name: "Ministral 3 8B",
    provider: "amazon-bedrock",
    family: "ministral",
    pricing: { input: 1.5e-7, output: 1.5e-7 },
    contextWindow: 128_000,
    maxOutput: 4096,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "openai.gpt-oss-safeguard-20b",
    name: "GPT OSS Safeguard 20B",
    provider: "amazon-bedrock",
    family: "gpt-oss",
    pricing: { input: 7e-8, output: 2e-7 },
    contextWindow: 128_000,
    maxOutput: 4096,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "amazon.nova-lite-v1:0",
    name: "Nova Lite",
    provider: "amazon-bedrock",
    family: "nova-lite",
    pricing: { input: 6e-8, output: 2.4e-7, cacheRead: 1.5e-8 },
    contextWindow: 300_000,
    maxOutput: 8192,
    modalities: { input: ["text", "image", "video"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "eu.anthropic.claude-sonnet-4-5-20250929-v1:0",
    name: "Claude Sonnet 4.5 (EU)",
    provider: "amazon-bedrock",
    family: "claude-sonnet",
    pricing: { input: 0.000_003, output: 0.000_015, cacheRead: 3e-7, cacheWrite: 0.000_003_75 },
    contextWindow: 200_000,
    maxOutput: 64_000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "mistral.pixtral-large-2502-v1:0",
    name: "Pixtral Large (25.02)",
    provider: "amazon-bedrock",
    family: "mistral",
    pricing: { input: 0.000_002, output: 0.000_006 },
    contextWindow: 128_000,
    maxOutput: 8192,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "google.gemma-3-12b-it",
    name: "Google Gemma 3 12B",
    provider: "amazon-bedrock",
    family: "gemma",
    pricing: { input: 5e-8, output: 1e-7 },
    contextWindow: 131_072,
    maxOutput: 8192,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: false, attachment: false, structuredOutput: false },
  },
  {
    id: "meta.llama3-1-8b-instruct-v1:0",
    name: "Llama 3.1 8B Instruct",
    provider: "amazon-bedrock",
    family: "llama",
    pricing: { input: 2.2e-7, output: 2.2e-7 },
    contextWindow: 128_000,
    maxOutput: 4096,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "mistral.devstral-2-123b",
    name: "Devstral 2 123B",
    provider: "amazon-bedrock",
    family: "devstral",
    pricing: { input: 4e-7, output: 0.000_002 },
    contextWindow: 256_000,
    maxOutput: 8192,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "anthropic.claude-sonnet-4-5-20250929-v1:0",
    name: "Claude Sonnet 4.5",
    provider: "amazon-bedrock",
    family: "claude-sonnet",
    pricing: { input: 0.000_003, output: 0.000_015, cacheRead: 3e-7, cacheWrite: 0.000_003_75 },
    contextWindow: 200_000,
    maxOutput: 64_000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "meta.llama4-maverick-17b-instruct-v1:0",
    name: "Llama 4 Maverick 17B Instruct",
    provider: "amazon-bedrock",
    family: "llama",
    pricing: { input: 2.4e-7, output: 9.7e-7 },
    contextWindow: 1_000_000,
    maxOutput: 16_384,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "mistral.ministral-3-14b-instruct",
    name: "Ministral 14B 3.0",
    provider: "amazon-bedrock",
    family: "ministral",
    pricing: { input: 2e-7, output: 2e-7 },
    contextWindow: 128_000,
    maxOutput: 4096,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "minimax.minimax-m2",
    name: "MiniMax M2",
    provider: "amazon-bedrock",
    family: "minimax",
    pricing: { input: 3e-7, output: 0.000_001_2 },
    contextWindow: 204_608,
    maxOutput: 128_000,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "amazon.nova-micro-v1:0",
    name: "Nova Micro",
    provider: "amazon-bedrock",
    family: "nova-micro",
    pricing: { input: 3.5e-8, output: 1.4e-7, cacheRead: 8.75e-9 },
    contextWindow: 128_000,
    maxOutput: 8192,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "anthropic.claude-3-5-sonnet-20241022-v2:0",
    name: "Claude Sonnet 3.5 v2",
    provider: "amazon-bedrock",
    family: "claude-sonnet",
    pricing: { input: 0.000_003, output: 0.000_015, cacheRead: 3e-7, cacheWrite: 0.000_003_75 },
    contextWindow: 200_000,
    maxOutput: 8192,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "nvidia.nemotron-nano-3-30b",
    name: "NVIDIA Nemotron Nano 3 30B",
    provider: "amazon-bedrock",
    family: "nemotron",
    pricing: { input: 6e-8, output: 2.4e-7 },
    contextWindow: 128_000,
    maxOutput: 4096,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "anthropic.claude-sonnet-4-20250514-v1:0",
    name: "Claude Sonnet 4",
    provider: "amazon-bedrock",
    family: "claude-sonnet",
    pricing: { input: 0.000_003, output: 0.000_015, cacheRead: 3e-7, cacheWrite: 0.000_003_75 },
    contextWindow: 200_000,
    maxOutput: 64_000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "qwen.qwen3-vl-235b-a22b",
    name: "Qwen/Qwen3-VL-235B-A22B-Instruct",
    provider: "amazon-bedrock",
    family: "qwen",
    pricing: { input: 3e-7, output: 0.000_001_5 },
    contextWindow: 262_000,
    maxOutput: 262_000,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: true },
  },
  {
    id: "global.anthropic.claude-opus-4-6-v1",
    name: "Claude Opus 4.6 (Global)",
    provider: "amazon-bedrock",
    family: "claude-opus",
    pricing: { input: 0.000_005, output: 0.000_025, cacheRead: 5e-7, cacheWrite: 0.000_006_25 },
    contextWindow: 200_000,
    maxOutput: 128_000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "writer.palmyra-x4-v1:0",
    name: "Palmyra X4",
    provider: "amazon-bedrock",
    family: "palmyra",
    pricing: { input: 0.000_002_5, output: 0.000_01 },
    contextWindow: 122_880,
    maxOutput: 8192,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "amazon.nova-pro-v1:0",
    name: "Nova Pro",
    provider: "amazon-bedrock",
    family: "nova-pro",
    pricing: { input: 8e-7, output: 0.000_003_2, cacheRead: 2e-7 },
    contextWindow: 300_000,
    maxOutput: 8192,
    modalities: { input: ["text", "image", "video"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "us.anthropic.claude-opus-4-5-20251101-v1:0",
    name: "Claude Opus 4.5 (US)",
    provider: "amazon-bedrock",
    family: "claude-opus",
    pricing: { input: 0.000_005, output: 0.000_025, cacheRead: 5e-7, cacheWrite: 0.000_006_25 },
    contextWindow: 200_000,
    maxOutput: 64_000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "meta.llama3-2-90b-instruct-v1:0",
    name: "Llama 3.2 90B Instruct",
    provider: "amazon-bedrock",
    family: "llama",
    pricing: { input: 7.2e-7, output: 7.2e-7 },
    contextWindow: 128_000,
    maxOutput: 4096,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "us.anthropic.claude-opus-4-6-v1",
    name: "Claude Opus 4.6 (US)",
    provider: "amazon-bedrock",
    family: "claude-opus",
    pricing: { input: 0.000_005, output: 0.000_025, cacheRead: 5e-7, cacheWrite: 0.000_006_25 },
    contextWindow: 200_000,
    maxOutput: 128_000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "google.gemma-3-4b-it",
    name: "Gemma 3 4B IT",
    provider: "amazon-bedrock",
    family: "gemma",
    pricing: { input: 4e-8, output: 8e-8 },
    contextWindow: 128_000,
    maxOutput: 4096,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "anthropic.claude-opus-4-6-v1",
    name: "Claude Opus 4.6",
    provider: "amazon-bedrock",
    family: "claude-opus",
    pricing: { input: 0.000_005, output: 0.000_025, cacheRead: 5e-7, cacheWrite: 0.000_006_25 },
    contextWindow: 200_000,
    maxOutput: 128_000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "zai.glm-4.7-flash",
    name: "GLM-4.7-Flash",
    provider: "amazon-bedrock",
    family: "glm-flash",
    pricing: { input: 7e-8, output: 4e-7 },
    contextWindow: 200_000,
    maxOutput: 131_072,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "anthropic.claude-opus-4-20250514-v1:0",
    name: "Claude Opus 4",
    provider: "amazon-bedrock",
    family: "claude-opus",
    pricing: { input: 0.000_015, output: 0.000_075, cacheRead: 0.000_001_5, cacheWrite: 0.000_018_75 },
    contextWindow: 200_000,
    maxOutput: 32_000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "global.anthropic.claude-sonnet-4-6",
    name: "Claude Sonnet 4.6 (Global)",
    provider: "amazon-bedrock",
    family: "claude-sonnet",
    pricing: { input: 0.000_003, output: 0.000_015, cacheRead: 3e-7, cacheWrite: 0.000_003_75 },
    contextWindow: 200_000,
    maxOutput: 64_000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "meta.llama3-2-1b-instruct-v1:0",
    name: "Llama 3.2 1B Instruct",
    provider: "amazon-bedrock",
    family: "llama",
    pricing: { input: 1e-7, output: 1e-7 },
    contextWindow: 131_000,
    maxOutput: 4096,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "anthropic.claude-opus-4-1-20250805-v1:0",
    name: "Claude Opus 4.1",
    provider: "amazon-bedrock",
    family: "claude-opus",
    pricing: { input: 0.000_015, output: 0.000_075, cacheRead: 0.000_001_5, cacheWrite: 0.000_018_75 },
    contextWindow: 200_000,
    maxOutput: 32_000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "meta.llama4-scout-17b-instruct-v1:0",
    name: "Llama 4 Scout 17B Instruct",
    provider: "amazon-bedrock",
    family: "llama",
    pricing: { input: 1.7e-7, output: 6.6e-7 },
    contextWindow: 3_500_000,
    maxOutput: 16_384,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "deepseek.v3.2",
    name: "DeepSeek-V3.2",
    provider: "amazon-bedrock",
    family: "deepseek",
    pricing: { input: 6.2e-7, output: 0.000_001_85 },
    contextWindow: 163_840,
    maxOutput: 81_920,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "deepseek.v3-v1:0",
    name: "DeepSeek-V3.1",
    provider: "amazon-bedrock",
    family: "deepseek",
    pricing: { input: 5.8e-7, output: 0.000_001_68 },
    contextWindow: 163_840,
    maxOutput: 81_920,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "mistral.ministral-3-3b-instruct",
    name: "Ministral 3 3B",
    provider: "amazon-bedrock",
    family: "ministral",
    pricing: { input: 1e-7, output: 1e-7 },
    contextWindow: 256_000,
    maxOutput: 8192,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "global.anthropic.claude-haiku-4-5-20251001-v1:0",
    name: "Claude Haiku 4.5 (Global)",
    provider: "amazon-bedrock",
    family: "claude-haiku",
    pricing: { input: 0.000_001, output: 0.000_005, cacheRead: 1e-7, cacheWrite: 0.000_001_25 },
    contextWindow: 200_000,
    maxOutput: 64_000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "nvidia.nemotron-nano-9b-v2",
    name: "NVIDIA Nemotron Nano 9B v2",
    provider: "amazon-bedrock",
    family: "nemotron",
    pricing: { input: 6e-8, output: 2.3e-7 },
    contextWindow: 128_000,
    maxOutput: 4096,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "writer.palmyra-x5-v1:0",
    name: "Palmyra X5",
    provider: "amazon-bedrock",
    family: "palmyra",
    pricing: { input: 6e-7, output: 0.000_006 },
    contextWindow: 1_040_000,
    maxOutput: 8192,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "meta.llama3-3-70b-instruct-v1:0",
    name: "Llama 3.3 70B Instruct",
    provider: "amazon-bedrock",
    family: "llama",
    pricing: { input: 7.2e-7, output: 7.2e-7 },
    contextWindow: 128_000,
    maxOutput: 4096,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "zai.glm-4.7",
    name: "GLM-4.7",
    provider: "amazon-bedrock",
    family: "glm",
    pricing: { input: 6e-7, output: 0.000_002_2 },
    contextWindow: 204_800,
    maxOutput: 131_072,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "moonshot.kimi-k2-thinking",
    name: "Kimi K2 Thinking",
    provider: "amazon-bedrock",
    family: "kimi-thinking",
    pricing: { input: 6e-7, output: 0.000_002_5 },
    contextWindow: 256_000,
    maxOutput: 256_000,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "anthropic.claude-3-haiku-20240307-v1:0",
    name: "Claude Haiku 3",
    provider: "amazon-bedrock",
    family: "claude-haiku",
    pricing: { input: 2.5e-7, output: 0.000_001_25 },
    contextWindow: 200_000,
    maxOutput: 4096,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "us.anthropic.claude-sonnet-4-5-20250929-v1:0",
    name: "Claude Sonnet 4.5 (US)",
    provider: "amazon-bedrock",
    family: "claude-sonnet",
    pricing: { input: 0.000_003, output: 0.000_015, cacheRead: 3e-7, cacheWrite: 0.000_003_75 },
    contextWindow: 200_000,
    maxOutput: 64_000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "openai.gpt-oss-20b-1:0",
    name: "gpt-oss-20b",
    provider: "amazon-bedrock",
    family: "gpt-oss",
    pricing: { input: 7e-8, output: 3e-7 },
    contextWindow: 128_000,
    maxOutput: 4096,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "us.anthropic.claude-sonnet-4-6",
    name: "Claude Sonnet 4.6 (US)",
    provider: "amazon-bedrock",
    family: "claude-sonnet",
    pricing: { input: 0.000_003, output: 0.000_015, cacheRead: 3e-7, cacheWrite: 0.000_003_75 },
    contextWindow: 200_000,
    maxOutput: 64_000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "meta.llama3-2-11b-instruct-v1:0",
    name: "Llama 3.2 11B Instruct",
    provider: "amazon-bedrock",
    family: "llama",
    pricing: { input: 1.6e-7, output: 1.6e-7 },
    contextWindow: 128_000,
    maxOutput: 4096,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "eu.anthropic.claude-opus-4-5-20251101-v1:0",
    name: "Claude Opus 4.5 (EU)",
    provider: "amazon-bedrock",
    family: "claude-opus",
    pricing: { input: 0.000_005, output: 0.000_025, cacheRead: 5e-7, cacheWrite: 0.000_006_25 },
    contextWindow: 200_000,
    maxOutput: 64_000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "meta.llama3-1-405b-instruct-v1:0",
    name: "Llama 3.1 405B Instruct",
    provider: "amazon-bedrock",
    family: "llama",
    pricing: { input: 0.000_002_4, output: 0.000_002_4 },
    contextWindow: 128_000,
    maxOutput: 4096,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen.qwen3-next-80b-a3b",
    name: "Qwen/Qwen3-Next-80B-A3B-Instruct",
    provider: "amazon-bedrock",
    family: "qwen",
    pricing: { input: 1.4e-7, output: 0.000_001_4 },
    contextWindow: 262_000,
    maxOutput: 262_000,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: true },
  },
  {
    id: "us.anthropic.claude-sonnet-4-20250514-v1:0",
    name: "Claude Sonnet 4 (US)",
    provider: "amazon-bedrock",
    family: "claude-sonnet",
    pricing: { input: 0.000_003, output: 0.000_015, cacheRead: 3e-7, cacheWrite: 0.000_003_75 },
    contextWindow: 200_000,
    maxOutput: 64_000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "qwen.qwen3-coder-30b-a3b-v1:0",
    name: "Qwen3 Coder 30B A3B Instruct",
    provider: "amazon-bedrock",
    family: "qwen",
    pricing: { input: 1.5e-7, output: 6e-7 },
    contextWindow: 262_144,
    maxOutput: 131_072,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "us.anthropic.claude-haiku-4-5-20251001-v1:0",
    name: "Claude Haiku 4.5 (US)",
    provider: "amazon-bedrock",
    family: "claude-haiku",
    pricing: { input: 0.000_001, output: 0.000_005, cacheRead: 1e-7, cacheWrite: 0.000_001_25 },
    contextWindow: 200_000,
    maxOutput: 64_000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "qwen.qwen3-235b-a22b-2507-v1:0",
    name: "Qwen3 235B A22B 2507",
    provider: "amazon-bedrock",
    family: "qwen",
    pricing: { input: 2.2e-7, output: 8.8e-7 },
    contextWindow: 262_144,
    maxOutput: 131_072,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "openai.gpt-oss-safeguard-120b",
    name: "GPT OSS Safeguard 120B",
    provider: "amazon-bedrock",
    family: "gpt-oss",
    pricing: { input: 1.5e-7, output: 6e-7 },
    contextWindow: 128_000,
    maxOutput: 4096,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "anthropic.claude-3-5-sonnet-20240620-v1:0",
    name: "Claude Sonnet 3.5",
    provider: "amazon-bedrock",
    family: "claude-sonnet",
    pricing: { input: 0.000_003, output: 0.000_015, cacheRead: 3e-7, cacheWrite: 0.000_003_75 },
    contextWindow: 200_000,
    maxOutput: 8192,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "mistral.voxtral-small-24b-2507",
    name: "Voxtral Small 24B 2507",
    provider: "amazon-bedrock",
    family: "mistral",
    pricing: { input: 1.5e-7, output: 3.5e-7 },
    contextWindow: 32_000,
    maxOutput: 8192,
    modalities: { input: ["text", "audio"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "anthropic.claude-haiku-4-5-20251001-v1:0",
    name: "Claude Haiku 4.5",
    provider: "amazon-bedrock",
    family: "claude-haiku",
    pricing: { input: 0.000_001, output: 0.000_005, cacheRead: 1e-7, cacheWrite: 0.000_001_25 },
    contextWindow: 200_000,
    maxOutput: 64_000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "meta.llama3-2-3b-instruct-v1:0",
    name: "Llama 3.2 3B Instruct",
    provider: "amazon-bedrock",
    family: "llama",
    pricing: { input: 1.5e-7, output: 1.5e-7 },
    contextWindow: 131_000,
    maxOutput: 4096,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "google.gemma-3-27b-it",
    name: "Google Gemma 3 27B Instruct",
    provider: "amazon-bedrock",
    family: "gemma",
    pricing: { input: 1.2e-7, output: 2e-7 },
    contextWindow: 202_752,
    maxOutput: 8192,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "us.anthropic.claude-opus-4-1-20250805-v1:0",
    name: "Claude Opus 4.1 (US)",
    provider: "amazon-bedrock",
    family: "claude-opus",
    pricing: { input: 0.000_015, output: 0.000_075, cacheRead: 0.000_001_5, cacheWrite: 0.000_018_75 },
    contextWindow: 200_000,
    maxOutput: 32_000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "global.anthropic.claude-sonnet-4-20250514-v1:0",
    name: "Claude Sonnet 4 (Global)",
    provider: "amazon-bedrock",
    family: "claude-sonnet",
    pricing: { input: 0.000_003, output: 0.000_015, cacheRead: 3e-7, cacheWrite: 0.000_003_75 },
    contextWindow: 200_000,
    maxOutput: 64_000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "anthropic.claude-3-5-haiku-20241022-v1:0",
    name: "Claude Haiku 3.5",
    provider: "amazon-bedrock",
    family: "claude-haiku",
    pricing: { input: 8e-7, output: 0.000_004, cacheRead: 8e-8, cacheWrite: 0.000_001 },
    contextWindow: 200_000,
    maxOutput: 8192,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "eu.anthropic.claude-sonnet-4-20250514-v1:0",
    name: "Claude Sonnet 4 (EU)",
    provider: "amazon-bedrock",
    family: "claude-sonnet",
    pricing: { input: 0.000_003, output: 0.000_015, cacheRead: 3e-7, cacheWrite: 0.000_003_75 },
    contextWindow: 200_000,
    maxOutput: 64_000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "anthropic.claude-opus-4-5-20251101-v1:0",
    name: "Claude Opus 4.5",
    provider: "amazon-bedrock",
    family: "claude-opus",
    pricing: { input: 0.000_005, output: 0.000_025, cacheRead: 5e-7, cacheWrite: 0.000_006_25 },
    contextWindow: 200_000,
    maxOutput: 64_000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "eu.anthropic.claude-opus-4-6-v1",
    name: "Claude Opus 4.6 (EU)",
    provider: "amazon-bedrock",
    family: "claude-opus",
    pricing: { input: 0.000_005, output: 0.000_025, cacheRead: 5e-7, cacheWrite: 0.000_006_25 },
    contextWindow: 200_000,
    maxOutput: 128_000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "amazon.nova-premier-v1:0",
    name: "Nova Premier",
    provider: "amazon-bedrock",
    family: "nova",
    pricing: { input: 0.000_002_5, output: 0.000_012_5 },
    contextWindow: 1_000_000,
    maxOutput: 16_384,
    modalities: { input: ["text", "image", "video"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "amazon.nova-2-lite-v1:0",
    name: "Nova 2 Lite",
    provider: "amazon-bedrock",
    family: "nova",
    pricing: { input: 3.3e-7, output: 0.000_002_75 },
    contextWindow: 128_000,
    maxOutput: 4096,
    modalities: { input: ["text", "image", "video"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "qwen.qwen3-32b-v1:0",
    name: "Qwen3 32B (dense)",
    provider: "amazon-bedrock",
    family: "qwen",
    pricing: { input: 1.5e-7, output: 6e-7 },
    contextWindow: 16_384,
    maxOutput: 16_384,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "mistral.magistral-small-2509",
    name: "Magistral Small 1.2",
    provider: "amazon-bedrock",
    family: "magistral",
    pricing: { input: 5e-7, output: 0.000_001_5 },
    contextWindow: 128_000,
    maxOutput: 40_000,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "moonshotai.kimi-k2.5",
    name: "Kimi K2.5",
    provider: "amazon-bedrock",
    family: "kimi",
    pricing: { input: 6e-7, output: 0.000_003 },
    contextWindow: 256_000,
    maxOutput: 256_000,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "mistral.voxtral-mini-3b-2507",
    name: "Voxtral Mini 3B 2507",
    provider: "amazon-bedrock",
    family: "mistral",
    pricing: { input: 4e-8, output: 4e-8 },
    contextWindow: 128_000,
    maxOutput: 4096,
    modalities: { input: ["audio", "text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "global.anthropic.claude-sonnet-4-5-20250929-v1:0",
    name: "Claude Sonnet 4.5 (Global)",
    provider: "amazon-bedrock",
    family: "claude-sonnet",
    pricing: { input: 0.000_003, output: 0.000_015, cacheRead: 3e-7, cacheWrite: 0.000_003_75 },
    contextWindow: 200_000,
    maxOutput: 64_000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
] as const satisfies readonly ModelDefinition[];
