// ──────────────────────────────────────────────────────────────
// ███████╗██╗   ██╗███╗   ██╗██╗  ██╗ █████╗ ██╗
// ██╔════╝██║   ██║████╗  ██║██║ ██╔╝██╔══██╗██║
// █████╗  ██║   ██║██╔██╗ ██║█████╔╝ ███████║██║
// ██╔══╝  ██║   ██║██║╚██╗██║██╔═██╗ ██╔══██║██║
// ██║     ╚██████╔╝██║ ╚████║██║  ██╗██║  ██║██║
// ╚═╝      ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝
//
// AUTO-GENERATED — DO NOT EDIT
// Source: https://models.dev
// Update: pnpm --filter=@funkai/models generate:models
// ──────────────────────────────────────────────────────────────

import type { ModelDefinition } from "../types.js";

export const ANTHROPIC_MODELS = [
  {
    id: "claude-opus-4-5-20251101",
    name: "Claude Opus 4.5",
    provider: "anthropic",
    family: "claude-opus",
    pricing: { input: 0.000005, output: 0.000025, cacheRead: 5e-7, cacheWrite: 0.00000625 },
    contextWindow: 200000,
    maxOutput: 64000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "claude-3-5-haiku-latest",
    name: "Claude Haiku 3.5 (latest)",
    provider: "anthropic",
    family: "claude-haiku",
    pricing: { input: 8e-7, output: 0.000004, cacheRead: 8e-8, cacheWrite: 0.000001 },
    contextWindow: 200000,
    maxOutput: 8192,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "claude-opus-4-1",
    name: "Claude Opus 4.1 (latest)",
    provider: "anthropic",
    family: "claude-opus",
    pricing: { input: 0.000015, output: 0.000075, cacheRead: 0.0000015, cacheWrite: 0.00001875 },
    contextWindow: 200000,
    maxOutput: 32000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "claude-3-5-sonnet-20241022",
    name: "Claude Sonnet 3.5 v2",
    provider: "anthropic",
    family: "claude-sonnet",
    pricing: { input: 0.000003, output: 0.000015, cacheRead: 3e-7, cacheWrite: 0.00000375 },
    contextWindow: 200000,
    maxOutput: 8192,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "claude-3-sonnet-20240229",
    name: "Claude Sonnet 3",
    provider: "anthropic",
    family: "claude-sonnet",
    pricing: { input: 0.000003, output: 0.000015, cacheRead: 3e-7, cacheWrite: 3e-7 },
    contextWindow: 200000,
    maxOutput: 4096,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "claude-opus-4-6",
    name: "Claude Opus 4.6",
    provider: "anthropic",
    family: "claude-opus",
    pricing: { input: 0.000005, output: 0.000025, cacheRead: 5e-7, cacheWrite: 0.00000625 },
    contextWindow: 1000000,
    maxOutput: 128000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "claude-sonnet-4-6",
    name: "Claude Sonnet 4.6",
    provider: "anthropic",
    family: "claude-sonnet",
    pricing: { input: 0.000003, output: 0.000015, cacheRead: 3e-7, cacheWrite: 0.00000375 },
    contextWindow: 1000000,
    maxOutput: 64000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "claude-sonnet-4-0",
    name: "Claude Sonnet 4 (latest)",
    provider: "anthropic",
    family: "claude-sonnet",
    pricing: { input: 0.000003, output: 0.000015, cacheRead: 3e-7, cacheWrite: 0.00000375 },
    contextWindow: 200000,
    maxOutput: 64000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "claude-opus-4-20250514",
    name: "Claude Opus 4",
    provider: "anthropic",
    family: "claude-opus",
    pricing: { input: 0.000015, output: 0.000075, cacheRead: 0.0000015, cacheWrite: 0.00001875 },
    contextWindow: 200000,
    maxOutput: 32000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "claude-sonnet-4-5-20250929",
    name: "Claude Sonnet 4.5",
    provider: "anthropic",
    family: "claude-sonnet",
    pricing: { input: 0.000003, output: 0.000015, cacheRead: 3e-7, cacheWrite: 0.00000375 },
    contextWindow: 200000,
    maxOutput: 64000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "claude-opus-4-0",
    name: "Claude Opus 4 (latest)",
    provider: "anthropic",
    family: "claude-opus",
    pricing: { input: 0.000015, output: 0.000075, cacheRead: 0.0000015, cacheWrite: 0.00001875 },
    contextWindow: 200000,
    maxOutput: 32000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "claude-3-5-haiku-20241022",
    name: "Claude Haiku 3.5",
    provider: "anthropic",
    family: "claude-haiku",
    pricing: { input: 8e-7, output: 0.000004, cacheRead: 8e-8, cacheWrite: 0.000001 },
    contextWindow: 200000,
    maxOutput: 8192,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "claude-3-5-sonnet-20240620",
    name: "Claude Sonnet 3.5",
    provider: "anthropic",
    family: "claude-sonnet",
    pricing: { input: 0.000003, output: 0.000015, cacheRead: 3e-7, cacheWrite: 0.00000375 },
    contextWindow: 200000,
    maxOutput: 8192,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "claude-3-7-sonnet-latest",
    name: "Claude Sonnet 3.7 (latest)",
    provider: "anthropic",
    family: "claude-sonnet",
    pricing: { input: 0.000003, output: 0.000015, cacheRead: 3e-7, cacheWrite: 0.00000375 },
    contextWindow: 200000,
    maxOutput: 64000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "claude-3-7-sonnet-20250219",
    name: "Claude Sonnet 3.7",
    provider: "anthropic",
    family: "claude-sonnet",
    pricing: { input: 0.000003, output: 0.000015, cacheRead: 3e-7, cacheWrite: 0.00000375 },
    contextWindow: 200000,
    maxOutput: 64000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "claude-3-haiku-20240307",
    name: "Claude Haiku 3",
    provider: "anthropic",
    family: "claude-haiku",
    pricing: { input: 2.5e-7, output: 0.00000125, cacheRead: 3e-8, cacheWrite: 3e-7 },
    contextWindow: 200000,
    maxOutput: 4096,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "claude-haiku-4-5-20251001",
    name: "Claude Haiku 4.5",
    provider: "anthropic",
    family: "claude-haiku",
    pricing: { input: 0.000001, output: 0.000005, cacheRead: 1e-7, cacheWrite: 0.00000125 },
    contextWindow: 200000,
    maxOutput: 64000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "claude-haiku-4-5",
    name: "Claude Haiku 4.5 (latest)",
    provider: "anthropic",
    family: "claude-haiku",
    pricing: { input: 0.000001, output: 0.000005, cacheRead: 1e-7, cacheWrite: 0.00000125 },
    contextWindow: 200000,
    maxOutput: 64000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "claude-opus-4-5",
    name: "Claude Opus 4.5 (latest)",
    provider: "anthropic",
    family: "claude-opus",
    pricing: { input: 0.000005, output: 0.000025, cacheRead: 5e-7, cacheWrite: 0.00000625 },
    contextWindow: 200000,
    maxOutput: 64000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "claude-3-opus-20240229",
    name: "Claude Opus 3",
    provider: "anthropic",
    family: "claude-opus",
    pricing: { input: 0.000015, output: 0.000075, cacheRead: 0.0000015, cacheWrite: 0.00001875 },
    contextWindow: 200000,
    maxOutput: 4096,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "claude-sonnet-4-5",
    name: "Claude Sonnet 4.5 (latest)",
    provider: "anthropic",
    family: "claude-sonnet",
    pricing: { input: 0.000003, output: 0.000015, cacheRead: 3e-7, cacheWrite: 0.00000375 },
    contextWindow: 200000,
    maxOutput: 64000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "claude-sonnet-4-20250514",
    name: "Claude Sonnet 4",
    provider: "anthropic",
    family: "claude-sonnet",
    pricing: { input: 0.000003, output: 0.000015, cacheRead: 3e-7, cacheWrite: 0.00000375 },
    contextWindow: 200000,
    maxOutput: 64000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "claude-opus-4-1-20250805",
    name: "Claude Opus 4.1",
    provider: "anthropic",
    family: "claude-opus",
    pricing: { input: 0.000015, output: 0.000075, cacheRead: 0.0000015, cacheWrite: 0.00001875 },
    contextWindow: 200000,
    maxOutput: 32000,
    modalities: { input: ["text", "image", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
] as const satisfies readonly ModelDefinition[];
