// ──────────────────────────────────────────────────────────────
// ███████╗██╗   ██╗███╗   ██╗██╗  ██╗ █████╗ ██╗
// ██╔════╝██║   ██║████╗  ██║██║ ██╔╝██╔══██╗██║
// █████╗  ██║   ██║██╔██╗ ██║█████╔╝ ███████║██║
// ██╔══╝  ██║   ██║██║╚██╗██║██╔═██╗ ██╔══██║██║
// ██║     ╚██████╔╝██║ ╚████║██║  ██╗██║  ██║██║
// ╚═╝      ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝
//
// AUTO-GENERATED — DO NOT EDIT
// Source: https://models.dev
// Update: pnpm --filter=@funkai/models generate:models
// ──────────────────────────────────────────────────────────────

import type { ModelDefinition } from '../types.js'

export const DEEPINFRA_MODELS = [
  { id: 'zai-org/GLM-4.7-Flash', name: 'GLM-4.7-Flash', provider: 'deepinfra', family: 'glm-flash', pricing: { input: 6e-8, output: 4.0000000000000003e-7 }, contextWindow: 202752, maxOutput: 16384, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'zai-org/GLM-4.6', name: 'GLM-4.6', provider: 'deepinfra', family: 'glm', pricing: { input: 4.3e-7, output: 0.00000174, cacheRead: 8e-8 }, contextWindow: 204800, maxOutput: 131072, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'zai-org/GLM-4.7', name: 'GLM-4.7', provider: 'deepinfra', family: 'glm', pricing: { input: 4.3e-7, output: 0.00000175, cacheRead: 8e-8 }, contextWindow: 202752, maxOutput: 16384, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'zai-org/GLM-4.6V', name: 'GLM-4.6V', provider: 'deepinfra', family: 'glm', pricing: { input: 3e-7, output: 9.000000000000001e-7 }, contextWindow: 204800, maxOutput: 131072, modalities: { input: ["text","image"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false } },
  { id: 'zai-org/GLM-4.5', name: 'GLM-4.5', provider: 'deepinfra', family: 'glm', pricing: { input: 6e-7, output: 0.0000022 }, contextWindow: 131072, maxOutput: 98304, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'zai-org/GLM-5', name: 'GLM-5', provider: 'deepinfra', family: 'glm', pricing: { input: 8.000000000000001e-7, output: 0.00000256, cacheRead: 1.6e-7 }, contextWindow: 202752, maxOutput: 16384, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'MiniMaxAI/MiniMax-M2.5', name: 'MiniMax M2.5', provider: 'deepinfra', family: 'minimax', pricing: { input: 2.7e-7, output: 9.499999999999999e-7, cacheRead: 3e-8, cacheWrite: 3.75e-7 }, contextWindow: 204800, maxOutput: 131072, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'MiniMaxAI/MiniMax-M2', name: 'MiniMax M2', provider: 'deepinfra', family: 'minimax', pricing: { input: 2.54e-7, output: 0.00000102 }, contextWindow: 262144, maxOutput: 32768, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'MiniMaxAI/MiniMax-M2.1', name: 'MiniMax M2.1', provider: 'deepinfra', family: '', pricing: { input: 2.8e-7, output: 0.0000012 }, contextWindow: 196608, maxOutput: 196608, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'deepseek-ai/DeepSeek-R1-0528', name: 'DeepSeek-R1-0528', provider: 'deepinfra', family: '', pricing: { input: 5e-7, output: 0.0000021499999999999997, cacheRead: 3.5e-7 }, contextWindow: 163840, maxOutput: 64000, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: false, attachment: false, structuredOutput: false } },
  { id: 'deepseek-ai/DeepSeek-V3.2', name: 'DeepSeek-V3.2', provider: 'deepinfra', family: '', pricing: { input: 2.6e-7, output: 3.8e-7, cacheRead: 1.3e-7 }, contextWindow: 163840, maxOutput: 64000, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'moonshotai/Kimi-K2-Instruct', name: 'Kimi K2', provider: 'deepinfra', family: 'kimi', pricing: { input: 5e-7, output: 0.000002 }, contextWindow: 131072, maxOutput: 32768, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'moonshotai/Kimi-K2-Instruct-0905', name: 'Kimi K2 0905', provider: 'deepinfra', family: 'kimi', pricing: { input: 4.0000000000000003e-7, output: 0.000002, cacheRead: 1.5e-7 }, contextWindow: 262144, maxOutput: 262144, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'moonshotai/Kimi-K2.5', name: 'Kimi K2.5', provider: 'deepinfra', family: 'kimi', pricing: { input: 5e-7, output: 0.0000028 }, contextWindow: 262144, maxOutput: 32768, modalities: { input: ["text","image","video"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: true } },
  { id: 'moonshotai/Kimi-K2-Thinking', name: 'Kimi K2 Thinking', provider: 'deepinfra', family: 'kimi-thinking', pricing: { input: 4.6999999999999995e-7, output: 0.000002 }, contextWindow: 131072, maxOutput: 32768, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'Qwen/Qwen3-Coder-480B-A35B-Instruct-Turbo', name: 'Qwen3 Coder 480B A35B Instruct Turbo', provider: 'deepinfra', family: 'qwen', pricing: { input: 3e-7, output: 0.0000012 }, contextWindow: 262144, maxOutput: 66536, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'Qwen/Qwen3-Coder-480B-A35B-Instruct', name: 'Qwen3 Coder 480B A35B Instruct', provider: 'deepinfra', family: 'qwen', pricing: { input: 4.0000000000000003e-7, output: 0.0000016000000000000001 }, contextWindow: 262144, maxOutput: 66536, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'openai/gpt-oss-120b', name: 'GPT OSS 120B', provider: 'deepinfra', family: 'gpt-oss', pricing: { input: 5.0000000000000004e-8, output: 2.4e-7 }, contextWindow: 131072, maxOutput: 16384, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'openai/gpt-oss-20b', name: 'GPT OSS 20B', provider: 'deepinfra', family: 'gpt-oss', pricing: { input: 3e-8, output: 1.4e-7 }, contextWindow: 131072, maxOutput: 16384, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'anthropic/claude-3-7-sonnet-latest', name: 'Claude Sonnet 3.7 (Latest)', provider: 'deepinfra', family: 'claude-sonnet', pricing: { input: 0.0000032999999999999997, output: 0.0000165, cacheRead: 3.3e-7 }, contextWindow: 200000, maxOutput: 64000, modalities: { input: ["text","image"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false } },
  { id: 'anthropic/claude-4-opus', name: 'Claude Opus 4', provider: 'deepinfra', family: 'claude-opus', pricing: { input: 0.0000165, output: 0.0000825 }, contextWindow: 200000, maxOutput: 32000, modalities: { input: ["text","image"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false } },
] as const satisfies readonly ModelDefinition[]
