// ──────────────────────────────────────────────────────────────
// ███████╗██╗   ██╗███╗   ██╗██╗  ██╗ █████╗ ██╗
// ██╔════╝██║   ██║████╗  ██║██║ ██╔╝██╔══██╗██║
// █████╗  ██║   ██║██╔██╗ ██║█████╔╝ ███████║██║
// ██╔══╝  ██║   ██║██║╚██╗██║██╔═██╗ ██╔══██║██║
// ██║     ╚██████╔╝██║ ╚████║██║  ██╗██║  ██║██║
// ╚═╝      ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝
//
// AUTO-GENERATED — DO NOT EDIT
// Source: https://models.dev
// Update: pnpm --filter=@funkai/models generate:models
// ──────────────────────────────────────────────────────────────

import type { ModelDefinition } from "../types.js";

export const FIREWORKS_AI_MODELS = [
  {
    id: "accounts/fireworks/models/kimi-k2-instruct",
    name: "Kimi K2 Instruct",
    provider: "fireworks-ai",
    family: "kimi",
    pricing: { input: 0.000_001, output: 0.000_003 },
    contextWindow: 128_000,
    maxOutput: 16_384,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "accounts/fireworks/models/glm-4p7",
    name: "GLM 4.7",
    provider: "fireworks-ai",
    family: "glm",
    pricing: { input: 6e-7, output: 0.000_002_2, cacheRead: 3e-7 },
    contextWindow: 198_000,
    maxOutput: 198_000,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "accounts/fireworks/models/glm-5",
    name: "GLM 5",
    provider: "fireworks-ai",
    family: "glm",
    pricing: { input: 0.000_001, output: 0.000_003_2, cacheRead: 5e-7 },
    contextWindow: 202_752,
    maxOutput: 131_072,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "accounts/fireworks/models/deepseek-v3p1",
    name: "DeepSeek V3.1",
    provider: "fireworks-ai",
    family: "deepseek",
    pricing: { input: 5.6e-7, output: 0.000_001_68 },
    contextWindow: 163_840,
    maxOutput: 163_840,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "accounts/fireworks/models/minimax-m2p1",
    name: "MiniMax-M2.1",
    provider: "fireworks-ai",
    family: "minimax",
    pricing: { input: 3e-7, output: 0.000_001_2, cacheRead: 3e-8 },
    contextWindow: 200_000,
    maxOutput: 200_000,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "accounts/fireworks/models/glm-4p5-air",
    name: "GLM 4.5 Air",
    provider: "fireworks-ai",
    family: "glm-air",
    pricing: { input: 2.2e-7, output: 8.8e-7 },
    contextWindow: 131_072,
    maxOutput: 131_072,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "accounts/fireworks/models/deepseek-v3p2",
    name: "DeepSeek V3.2",
    provider: "fireworks-ai",
    family: "deepseek",
    pricing: { input: 5.6e-7, output: 0.000_001_68, cacheRead: 2.8e-7 },
    contextWindow: 160_000,
    maxOutput: 160_000,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "accounts/fireworks/models/minimax-m2p5",
    name: "MiniMax-M2.5",
    provider: "fireworks-ai",
    family: "minimax",
    pricing: { input: 3e-7, output: 0.000_001_2, cacheRead: 3e-8 },
    contextWindow: 196_608,
    maxOutput: 196_608,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "accounts/fireworks/models/gpt-oss-120b",
    name: "GPT OSS 120B",
    provider: "fireworks-ai",
    family: "gpt-oss",
    pricing: { input: 1.5e-7, output: 6e-7 },
    contextWindow: 131_072,
    maxOutput: 32_768,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "accounts/fireworks/models/kimi-k2p5",
    name: "Kimi K2.5",
    provider: "fireworks-ai",
    family: "kimi-thinking",
    pricing: { input: 6e-7, output: 0.000_003, cacheRead: 1e-7 },
    contextWindow: 256_000,
    maxOutput: 256_000,
    modalities: { input: ["text", "image", "video"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "accounts/fireworks/models/kimi-k2-thinking",
    name: "Kimi K2 Thinking",
    provider: "fireworks-ai",
    family: "kimi-thinking",
    pricing: { input: 6e-7, output: 0.000_002_5, cacheRead: 3e-7 },
    contextWindow: 256_000,
    maxOutput: 256_000,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "accounts/fireworks/models/glm-4p5",
    name: "GLM 4.5",
    provider: "fireworks-ai",
    family: "glm",
    pricing: { input: 5.5e-7, output: 0.000_002_19 },
    contextWindow: 131_072,
    maxOutput: 131_072,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "accounts/fireworks/models/gpt-oss-20b",
    name: "GPT OSS 20B",
    provider: "fireworks-ai",
    family: "gpt-oss",
    pricing: { input: 5e-8, output: 2e-7 },
    contextWindow: 131_072,
    maxOutput: 32_768,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
] as const satisfies readonly ModelDefinition[];
