// ──────────────────────────────────────────────────────────────
// ███████╗██╗   ██╗███╗   ██╗██╗  ██╗ █████╗ ██╗
// ██╔════╝██║   ██║████╗  ██║██║ ██╔╝██╔══██╗██║
// █████╗  ██║   ██║██╔██╗ ██║█████╔╝ ███████║██║
// ██╔══╝  ██║   ██║██║╚██╗██║██╔═██╗ ██╔══██║██║
// ██║     ╚██████╔╝██║ ╚████║██║  ██╗██║  ██║██║
// ╚═╝      ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝
//
// AUTO-GENERATED — DO NOT EDIT
// Source: https://models.dev
// Update: pnpm --filter=@funkai/models generate:models
// ──────────────────────────────────────────────────────────────

import type { ModelDefinition } from '../types.js'

export const GOOGLE_VERTEX_MODELS = [
  { id: 'gemini-embedding-001', name: 'Gemini Embedding 001', provider: 'google-vertex', family: 'gemini', pricing: { input: 1.5e-7, output: 0 }, contextWindow: 2048, maxOutput: 3072, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: false, attachment: false, structuredOutput: false } },
  { id: 'gemini-2.5-flash-lite-preview-09-2025', name: 'Gemini 2.5 Flash Lite Preview 09-25', provider: 'google-vertex', family: 'gemini-flash-lite', pricing: { input: 1.0000000000000001e-7, output: 4.0000000000000003e-7, cacheRead: 2.5000000000000002e-8 }, contextWindow: 1048576, maxOutput: 65536, modalities: { input: ["text","image","audio","video","pdf"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false } },
  { id: 'gemini-3.1-pro-preview-customtools', name: 'Gemini 3.1 Pro Preview Custom Tools', provider: 'google-vertex', family: 'gemini-pro', pricing: { input: 0.000002, output: 0.000012, cacheRead: 2.0000000000000002e-7 }, contextWindow: 1048576, maxOutput: 65536, modalities: { input: ["text","image","video","audio","pdf"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: true } },
  { id: 'gemini-2.5-pro-preview-06-05', name: 'Gemini 2.5 Pro Preview 06-05', provider: 'google-vertex', family: 'gemini-pro', pricing: { input: 0.00000125, output: 0.00001, cacheRead: 3.1e-7 }, contextWindow: 1048576, maxOutput: 65536, modalities: { input: ["text","image","audio","video","pdf"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false } },
  { id: 'gemini-2.5-flash-preview-04-17', name: 'Gemini 2.5 Flash Preview 04-17', provider: 'google-vertex', family: 'gemini-flash', pricing: { input: 1.5e-7, output: 6e-7, cacheRead: 3.75e-8 }, contextWindow: 1048576, maxOutput: 65536, modalities: { input: ["text","image","audio","video","pdf"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false } },
  { id: 'gemini-2.5-flash-preview-09-2025', name: 'Gemini 2.5 Flash Preview 09-25', provider: 'google-vertex', family: 'gemini-flash', pricing: { input: 3e-7, output: 0.0000025, cacheRead: 7.5e-8, cacheWrite: 3.8300000000000003e-7 }, contextWindow: 1048576, maxOutput: 65536, modalities: { input: ["text","image","audio","video","pdf"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false } },
  { id: 'gemini-2.5-pro-preview-05-06', name: 'Gemini 2.5 Pro Preview 05-06', provider: 'google-vertex', family: 'gemini-pro', pricing: { input: 0.00000125, output: 0.00001, cacheRead: 3.1e-7 }, contextWindow: 1048576, maxOutput: 65536, modalities: { input: ["text","image","audio","video","pdf"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false } },
  { id: 'gemini-2.5-flash-preview-05-20', name: 'Gemini 2.5 Flash Preview 05-20', provider: 'google-vertex', family: 'gemini-flash', pricing: { input: 1.5e-7, output: 6e-7, cacheRead: 3.75e-8 }, contextWindow: 1048576, maxOutput: 65536, modalities: { input: ["text","image","audio","video","pdf"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false } },
  { id: 'gemini-2.5-flash', name: 'Gemini 2.5 Flash', provider: 'google-vertex', family: 'gemini-flash', pricing: { input: 3e-7, output: 0.0000025, cacheRead: 7.5e-8, cacheWrite: 3.8300000000000003e-7 }, contextWindow: 1048576, maxOutput: 65536, modalities: { input: ["text","image","audio","video","pdf"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false } },
  { id: 'gemini-3-flash-preview', name: 'Gemini 3 Flash Preview', provider: 'google-vertex', family: 'gemini-flash', pricing: { input: 5e-7, output: 0.000003, cacheRead: 5.0000000000000004e-8 }, contextWindow: 1048576, maxOutput: 65536, modalities: { input: ["text","image","video","audio","pdf"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: true } },
  { id: 'gemini-2.5-flash-lite', name: 'Gemini 2.5 Flash Lite', provider: 'google-vertex', family: 'gemini-flash-lite', pricing: { input: 1.0000000000000001e-7, output: 4.0000000000000003e-7, cacheRead: 2.5000000000000002e-8 }, contextWindow: 1048576, maxOutput: 65536, modalities: { input: ["text","image","audio","video","pdf"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false } },
  { id: 'gemini-3.1-pro-preview', name: 'Gemini 3.1 Pro Preview', provider: 'google-vertex', family: 'gemini-pro', pricing: { input: 0.000002, output: 0.000012, cacheRead: 2.0000000000000002e-7 }, contextWindow: 1048576, maxOutput: 65536, modalities: { input: ["text","image","video","audio","pdf"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: true } },
  { id: 'gemini-flash-latest', name: 'Gemini Flash Latest', provider: 'google-vertex', family: 'gemini-flash', pricing: { input: 3e-7, output: 0.0000025, cacheRead: 7.5e-8, cacheWrite: 3.8300000000000003e-7 }, contextWindow: 1048576, maxOutput: 65536, modalities: { input: ["text","image","audio","video","pdf"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false } },
  { id: 'gemini-2.5-flash-lite-preview-06-17', name: 'Gemini 2.5 Flash Lite Preview 06-17', provider: 'google-vertex', family: 'gemini-flash-lite', pricing: { input: 1.0000000000000001e-7, output: 4.0000000000000003e-7, cacheRead: 2.5000000000000002e-8 }, contextWindow: 65536, maxOutput: 65536, modalities: { input: ["text","image","audio","video","pdf"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false } },
  { id: 'gemini-3-pro-preview', name: 'Gemini 3 Pro Preview', provider: 'google-vertex', family: 'gemini-pro', pricing: { input: 0.000002, output: 0.000012, cacheRead: 2.0000000000000002e-7 }, contextWindow: 1048576, maxOutput: 65536, modalities: { input: ["text","image","video","audio","pdf"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: true } },
  { id: 'gemini-2.0-flash-lite', name: 'Gemini 2.0 Flash Lite', provider: 'google-vertex', family: 'gemini-flash-lite', pricing: { input: 7.5e-8, output: 3e-7 }, contextWindow: 1048576, maxOutput: 8192, modalities: { input: ["text","image","audio","video","pdf"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false } },
  { id: 'gemini-flash-lite-latest', name: 'Gemini Flash-Lite Latest', provider: 'google-vertex', family: 'gemini-flash-lite', pricing: { input: 1.0000000000000001e-7, output: 4.0000000000000003e-7, cacheRead: 2.5000000000000002e-8 }, contextWindow: 1048576, maxOutput: 65536, modalities: { input: ["text","image","audio","video","pdf"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false } },
  { id: 'gemini-2.5-pro', name: 'Gemini 2.5 Pro', provider: 'google-vertex', family: 'gemini-pro', pricing: { input: 0.00000125, output: 0.00001, cacheRead: 3.1e-7 }, contextWindow: 1048576, maxOutput: 65536, modalities: { input: ["text","image","audio","video","pdf"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false } },
  { id: 'gemini-2.0-flash', name: 'Gemini 2.0 Flash', provider: 'google-vertex', family: 'gemini-flash', pricing: { input: 1.5e-7, output: 6e-7, cacheRead: 2.5000000000000002e-8 }, contextWindow: 1048576, maxOutput: 8192, modalities: { input: ["text","image","audio","video","pdf"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false } },
  { id: 'zai-org/glm-5-maas', name: 'GLM-5', provider: 'google-vertex', family: 'glm', pricing: { input: 0.000001, output: 0.0000032000000000000003, cacheRead: 1.0000000000000001e-7 }, contextWindow: 202752, maxOutput: 131072, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'zai-org/glm-4.7-maas', name: 'GLM-4.7', provider: 'google-vertex', family: 'glm', pricing: { input: 6e-7, output: 0.0000022 }, contextWindow: 200000, maxOutput: 128000, modalities: { input: ["text","pdf"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: true } },
  { id: 'deepseek-ai/deepseek-v3.1-maas', name: 'DeepSeek V3.1', provider: 'google-vertex', family: 'deepseek', pricing: { input: 6e-7, output: 0.0000017 }, contextWindow: 163840, maxOutput: 32768, modalities: { input: ["text","pdf"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: true } },
  { id: 'qwen/qwen3-235b-a22b-instruct-2507-maas', name: 'Qwen3 235B A22B Instruct', provider: 'google-vertex', family: 'qwen', pricing: { input: 2.2e-7, output: 8.8e-7 }, contextWindow: 262144, maxOutput: 16384, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: true } },
  { id: 'meta/llama-4-maverick-17b-128e-instruct-maas', name: 'Llama 4 Maverick 17B 128E Instruct', provider: 'google-vertex', family: 'llama', pricing: { input: 3.5e-7, output: 0.00000115 }, contextWindow: 524288, maxOutput: 8192, modalities: { input: ["text","image"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: true } },
  { id: 'meta/llama-3.3-70b-instruct-maas', name: 'Llama 3.3 70B Instruct', provider: 'google-vertex', family: 'llama', pricing: { input: 7.2e-7, output: 7.2e-7 }, contextWindow: 128000, maxOutput: 8192, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: true } },
  { id: 'openai/gpt-oss-20b-maas', name: 'GPT OSS 20B', provider: 'google-vertex', family: 'gpt-oss', pricing: { input: 7e-8, output: 2.5e-7 }, contextWindow: 131072, maxOutput: 32768, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'openai/gpt-oss-120b-maas', name: 'GPT OSS 120B', provider: 'google-vertex', family: 'gpt-oss', pricing: { input: 9e-8, output: 3.6e-7 }, contextWindow: 131072, maxOutput: 32768, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
] as const satisfies readonly ModelDefinition[]
