// ──────────────────────────────────────────────────────────────
// ███████╗██╗   ██╗███╗   ██╗██╗  ██╗ █████╗ ██╗
// ██╔════╝██║   ██║████╗  ██║██║ ██╔╝██╔══██╗██║
// █████╗  ██║   ██║██╔██╗ ██║█████╔╝ ███████║██║
// ██╔══╝  ██║   ██║██║╚██╗██║██╔═██╗ ██╔══██║██║
// ██║     ╚██████╔╝██║ ╚████║██║  ██╗██║  ██║██║
// ╚═╝      ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝
//
// AUTO-GENERATED — DO NOT EDIT
// Source: https://models.dev
// Update: pnpm --filter=@funkai/models generate:models
// ──────────────────────────────────────────────────────────────

import type { ModelDefinition } from "../types.js";

export const GOOGLE_MODELS = [
  {
    id: "gemini-embedding-001",
    name: "Gemini Embedding 001",
    provider: "google",
    family: "gemini",
    pricing: { input: 1.5e-7, output: 0 },
    contextWindow: 2048,
    maxOutput: 3072,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: false, attachment: false, structuredOutput: false },
  },
  {
    id: "gemini-2.5-flash-lite-preview-09-2025",
    name: "Gemini 2.5 Flash Lite Preview 09-25",
    provider: "google",
    family: "gemini-flash-lite",
    pricing: {
      input: 1.0000000000000001e-7,
      output: 4.0000000000000003e-7,
      cacheRead: 2.5000000000000002e-8,
    },
    contextWindow: 1048576,
    maxOutput: 65536,
    modalities: { input: ["text", "image", "audio", "video", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: true },
  },
  {
    id: "gemini-3.1-pro-preview-customtools",
    name: "Gemini 3.1 Pro Preview Custom Tools",
    provider: "google",
    family: "gemini-pro",
    pricing: { input: 0.000002, output: 0.000012, cacheRead: 2.0000000000000002e-7 },
    contextWindow: 1048576,
    maxOutput: 65536,
    modalities: { input: ["text", "image", "video", "audio", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: true },
  },
  {
    id: "gemini-2.5-pro-preview-06-05",
    name: "Gemini 2.5 Pro Preview 06-05",
    provider: "google",
    family: "gemini-pro",
    pricing: { input: 0.00000125, output: 0.00001, cacheRead: 3.1e-7 },
    contextWindow: 1048576,
    maxOutput: 65536,
    modalities: { input: ["text", "image", "audio", "video", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: true },
  },
  {
    id: "gemini-2.5-flash-preview-04-17",
    name: "Gemini 2.5 Flash Preview 04-17",
    provider: "google",
    family: "gemini-flash",
    pricing: { input: 1.5e-7, output: 6e-7, cacheRead: 3.75e-8 },
    contextWindow: 1048576,
    maxOutput: 65536,
    modalities: { input: ["text", "image", "audio", "video", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "gemini-2.5-flash-preview-09-2025",
    name: "Gemini 2.5 Flash Preview 09-25",
    provider: "google",
    family: "gemini-flash",
    pricing: { input: 3e-7, output: 0.0000025, cacheRead: 7.5e-8 },
    contextWindow: 1048576,
    maxOutput: 65536,
    modalities: { input: ["text", "image", "audio", "video", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: true },
  },
  {
    id: "gemini-2.5-pro-preview-05-06",
    name: "Gemini 2.5 Pro Preview 05-06",
    provider: "google",
    family: "gemini-pro",
    pricing: { input: 0.00000125, output: 0.00001, cacheRead: 3.1e-7 },
    contextWindow: 1048576,
    maxOutput: 65536,
    modalities: { input: ["text", "image", "audio", "video", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: true },
  },
  {
    id: "gemini-2.5-flash-preview-05-20",
    name: "Gemini 2.5 Flash Preview 05-20",
    provider: "google",
    family: "gemini-flash",
    pricing: { input: 1.5e-7, output: 6e-7, cacheRead: 3.75e-8 },
    contextWindow: 1048576,
    maxOutput: 65536,
    modalities: { input: ["text", "image", "audio", "video", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: true },
  },
  {
    id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    provider: "google",
    family: "gemini-flash",
    pricing: { input: 3e-7, output: 0.0000025, cacheRead: 7.5e-8 },
    contextWindow: 1048576,
    maxOutput: 65536,
    modalities: { input: ["text", "image", "audio", "video", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: true },
  },
  {
    id: "gemini-3.1-flash-image-preview",
    name: "Gemini 3.1 Flash Image (Preview)",
    provider: "google",
    family: "gemini-flash",
    pricing: { input: 2.5e-7, output: 0.00006 },
    contextWindow: 131072,
    maxOutput: 32768,
    modalities: { input: ["text", "image", "pdf"], output: ["text", "image"] },
    capabilities: { reasoning: true, toolCall: false, attachment: true, structuredOutput: false },
  },
  {
    id: "gemini-3.1-flash-lite-preview",
    name: "Gemini 3.1 Flash Lite Preview",
    provider: "google",
    family: "gemini-flash-lite",
    pricing: { input: 5e-7, output: 0.000003, cacheRead: 5.0000000000000004e-8 },
    contextWindow: 1048576,
    maxOutput: 65536,
    modalities: { input: ["text", "image", "video", "audio", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: true },
  },
  {
    id: "gemini-live-2.5-flash",
    name: "Gemini Live 2.5 Flash",
    provider: "google",
    family: "gemini-flash",
    pricing: { input: 5e-7, output: 0.000002 },
    contextWindow: 128000,
    maxOutput: 8000,
    modalities: { input: ["text", "image", "audio", "video"], output: ["text", "audio"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "gemini-3-flash-preview",
    name: "Gemini 3 Flash Preview",
    provider: "google",
    family: "gemini-flash",
    pricing: { input: 5e-7, output: 0.000003, cacheRead: 5.0000000000000004e-8 },
    contextWindow: 1048576,
    maxOutput: 65536,
    modalities: { input: ["text", "image", "video", "audio", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: true },
  },
  {
    id: "gemini-live-2.5-flash-preview-native-audio",
    name: "Gemini Live 2.5 Flash Preview Native Audio",
    provider: "google",
    family: "gemini-flash",
    pricing: { input: 5e-7, output: 0.000002 },
    contextWindow: 131072,
    maxOutput: 65536,
    modalities: { input: ["text", "audio", "video"], output: ["text", "audio"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "gemini-2.5-flash-lite",
    name: "Gemini 2.5 Flash Lite",
    provider: "google",
    family: "gemini-flash-lite",
    pricing: {
      input: 1.0000000000000001e-7,
      output: 4.0000000000000003e-7,
      cacheRead: 2.5000000000000002e-8,
    },
    contextWindow: 1048576,
    maxOutput: 65536,
    modalities: { input: ["text", "image", "audio", "video", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: true },
  },
  {
    id: "gemini-2.5-flash-preview-tts",
    name: "Gemini 2.5 Flash Preview TTS",
    provider: "google",
    family: "gemini-flash",
    pricing: { input: 5e-7, output: 0.00001 },
    contextWindow: 8000,
    maxOutput: 16000,
    modalities: { input: ["text"], output: ["audio"] },
    capabilities: { reasoning: false, toolCall: false, attachment: false, structuredOutput: false },
  },
  {
    id: "gemini-3.1-pro-preview",
    name: "Gemini 3.1 Pro Preview",
    provider: "google",
    family: "gemini-pro",
    pricing: { input: 0.000002, output: 0.000012, cacheRead: 2.0000000000000002e-7 },
    contextWindow: 1048576,
    maxOutput: 65536,
    modalities: { input: ["text", "image", "video", "audio", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: true },
  },
  {
    id: "gemini-flash-latest",
    name: "Gemini Flash Latest",
    provider: "google",
    family: "gemini-flash",
    pricing: { input: 3e-7, output: 0.0000025, cacheRead: 7.5e-8 },
    contextWindow: 1048576,
    maxOutput: 65536,
    modalities: { input: ["text", "image", "audio", "video", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: true },
  },
  {
    id: "gemini-2.5-flash-lite-preview-06-17",
    name: "Gemini 2.5 Flash Lite Preview 06-17",
    provider: "google",
    family: "gemini-flash-lite",
    pricing: {
      input: 1.0000000000000001e-7,
      output: 4.0000000000000003e-7,
      cacheRead: 2.5000000000000002e-8,
    },
    contextWindow: 1048576,
    maxOutput: 65536,
    modalities: { input: ["text", "image", "audio", "video", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "gemini-2.5-flash-image",
    name: "Gemini 2.5 Flash Image",
    provider: "google",
    family: "gemini-flash",
    pricing: { input: 3e-7, output: 0.00003, cacheRead: 7.5e-8 },
    contextWindow: 32768,
    maxOutput: 32768,
    modalities: { input: ["text", "image"], output: ["text", "image"] },
    capabilities: { reasoning: true, toolCall: false, attachment: true, structuredOutput: false },
  },
  {
    id: "gemini-2.5-pro-preview-tts",
    name: "Gemini 2.5 Pro Preview TTS",
    provider: "google",
    family: "gemini-flash",
    pricing: { input: 0.000001, output: 0.00002 },
    contextWindow: 8000,
    maxOutput: 16000,
    modalities: { input: ["text"], output: ["audio"] },
    capabilities: { reasoning: false, toolCall: false, attachment: false, structuredOutput: false },
  },
  {
    id: "gemini-2.5-flash-image-preview",
    name: "Gemini 2.5 Flash Image (Preview)",
    provider: "google",
    family: "gemini-flash",
    pricing: { input: 3e-7, output: 0.00003, cacheRead: 7.5e-8 },
    contextWindow: 32768,
    maxOutput: 32768,
    modalities: { input: ["text", "image"], output: ["text", "image"] },
    capabilities: { reasoning: true, toolCall: false, attachment: true, structuredOutput: false },
  },
  {
    id: "gemini-1.5-flash-8b",
    name: "Gemini 1.5 Flash-8B",
    provider: "google",
    family: "gemini-flash",
    pricing: { input: 3.75e-8, output: 1.5e-7, cacheRead: 1e-8 },
    contextWindow: 1000000,
    maxOutput: 8192,
    modalities: { input: ["text", "image", "audio", "video"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "gemini-3-pro-preview",
    name: "Gemini 3 Pro Preview",
    provider: "google",
    family: "gemini-pro",
    pricing: { input: 0.000002, output: 0.000012, cacheRead: 2.0000000000000002e-7 },
    contextWindow: 1000000,
    maxOutput: 64000,
    modalities: { input: ["text", "image", "video", "audio", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: true },
  },
  {
    id: "gemini-2.0-flash-lite",
    name: "Gemini 2.0 Flash Lite",
    provider: "google",
    family: "gemini-flash-lite",
    pricing: { input: 7.5e-8, output: 3e-7 },
    contextWindow: 1048576,
    maxOutput: 8192,
    modalities: { input: ["text", "image", "audio", "video", "pdf"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: true },
  },
  {
    id: "gemini-1.5-flash",
    name: "Gemini 1.5 Flash",
    provider: "google",
    family: "gemini-flash",
    pricing: { input: 7.5e-8, output: 3e-7, cacheRead: 1.875e-8 },
    contextWindow: 1000000,
    maxOutput: 8192,
    modalities: { input: ["text", "image", "audio", "video"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "gemini-flash-lite-latest",
    name: "Gemini Flash-Lite Latest",
    provider: "google",
    family: "gemini-flash-lite",
    pricing: {
      input: 1.0000000000000001e-7,
      output: 4.0000000000000003e-7,
      cacheRead: 2.5000000000000002e-8,
    },
    contextWindow: 1048576,
    maxOutput: 65536,
    modalities: { input: ["text", "image", "audio", "video", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: true },
  },
  {
    id: "gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    provider: "google",
    family: "gemini-pro",
    pricing: { input: 0.00000125, output: 0.00001, cacheRead: 3.1e-7 },
    contextWindow: 1048576,
    maxOutput: 65536,
    modalities: { input: ["text", "image", "audio", "video", "pdf"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: true },
  },
  {
    id: "gemini-2.0-flash",
    name: "Gemini 2.0 Flash",
    provider: "google",
    family: "gemini-flash",
    pricing: {
      input: 1.0000000000000001e-7,
      output: 4.0000000000000003e-7,
      cacheRead: 2.5000000000000002e-8,
    },
    contextWindow: 1048576,
    maxOutput: 8192,
    modalities: { input: ["text", "image", "audio", "video", "pdf"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: true },
  },
  {
    id: "gemini-1.5-pro",
    name: "Gemini 1.5 Pro",
    provider: "google",
    family: "gemini-pro",
    pricing: { input: 0.00000125, output: 0.000005, cacheRead: 3.125e-7 },
    contextWindow: 1000000,
    maxOutput: 8192,
    modalities: { input: ["text", "image", "audio", "video"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false },
  },
] as const satisfies readonly ModelDefinition[];
