// ──────────────────────────────────────────────────────────────
// ███████╗██╗   ██╗███╗   ██╗██╗  ██╗ █████╗ ██╗
// ██╔════╝██║   ██║████╗  ██║██║ ██╔╝██╔══██╗██║
// █████╗  ██║   ██║██╔██╗ ██║█████╔╝ ███████║██║
// ██╔══╝  ██║   ██║██║╚██╗██║██╔═██╗ ██╔══██║██║
// ██║     ╚██████╔╝██║ ╚████║██║  ██╗██║  ██║██║
// ╚═╝      ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝
//
// AUTO-GENERATED — DO NOT EDIT
// Source: https://models.dev
// Update: pnpm --filter=@funkai/models generate:models
// ──────────────────────────────────────────────────────────────

import type { ModelDefinition } from '../types.js'

export const GROQ_MODELS = [
  { id: 'llama3-70b-8192', name: 'Llama 3 70B', provider: 'groq', family: 'llama', pricing: { input: 5.9e-7, output: 7.900000000000001e-7 }, contextWindow: 8192, maxOutput: 8192, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'qwen-qwq-32b', name: 'Qwen QwQ 32B', provider: 'groq', family: 'qwen', pricing: { input: 2.9e-7, output: 3.9e-7 }, contextWindow: 131072, maxOutput: 16384, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'llama-3.1-8b-instant', name: 'Llama 3.1 8B Instant', provider: 'groq', family: 'llama', pricing: { input: 5.0000000000000004e-8, output: 8e-8 }, contextWindow: 131072, maxOutput: 131072, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'llama-guard-3-8b', name: 'Llama Guard 3 8B', provider: 'groq', family: 'llama', pricing: { input: 2.0000000000000002e-7, output: 2.0000000000000002e-7 }, contextWindow: 8192, maxOutput: 8192, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: false, attachment: false, structuredOutput: false } },
  { id: 'deepseek-r1-distill-llama-70b', name: 'DeepSeek R1 Distill Llama 70B', provider: 'groq', family: 'deepseek-thinking', pricing: { input: 7.5e-7, output: 9.9e-7 }, contextWindow: 131072, maxOutput: 8192, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'llama3-8b-8192', name: 'Llama 3 8B', provider: 'groq', family: 'llama', pricing: { input: 5.0000000000000004e-8, output: 8e-8 }, contextWindow: 8192, maxOutput: 8192, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'mistral-saba-24b', name: 'Mistral Saba 24B', provider: 'groq', family: 'mistral', pricing: { input: 7.900000000000001e-7, output: 7.900000000000001e-7 }, contextWindow: 32768, maxOutput: 32768, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'llama-3.3-70b-versatile', name: 'Llama 3.3 70B Versatile', provider: 'groq', family: 'llama', pricing: { input: 5.9e-7, output: 7.900000000000001e-7 }, contextWindow: 131072, maxOutput: 32768, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'gemma2-9b-it', name: 'Gemma 2 9B', provider: 'groq', family: 'gemma', pricing: { input: 2.0000000000000002e-7, output: 2.0000000000000002e-7 }, contextWindow: 8192, maxOutput: 8192, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'moonshotai/kimi-k2-instruct', name: 'Kimi K2 Instruct', provider: 'groq', family: 'kimi', pricing: { input: 0.000001, output: 0.000003 }, contextWindow: 131072, maxOutput: 16384, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'moonshotai/kimi-k2-instruct-0905', name: 'Kimi K2 Instruct 0905', provider: 'groq', family: 'kimi', pricing: { input: 0.000001, output: 0.000003 }, contextWindow: 262144, maxOutput: 16384, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: true } },
  { id: 'qwen/qwen3-32b', name: 'Qwen3 32B', provider: 'groq', family: 'qwen', pricing: { input: 2.9e-7, output: 5.9e-7 }, contextWindow: 131072, maxOutput: 16384, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'meta-llama/llama-4-scout-17b-16e-instruct', name: 'Llama 4 Scout 17B', provider: 'groq', family: 'llama', pricing: { input: 1.1e-7, output: 3.4000000000000003e-7 }, contextWindow: 131072, maxOutput: 8192, modalities: { input: ["text","image"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: true } },
  { id: 'meta-llama/llama-guard-4-12b', name: 'Llama Guard 4 12B', provider: 'groq', family: 'llama', pricing: { input: 2.0000000000000002e-7, output: 2.0000000000000002e-7 }, contextWindow: 131072, maxOutput: 1024, modalities: { input: ["text","image"], output: ["text"] }, capabilities: { reasoning: false, toolCall: false, attachment: false, structuredOutput: false } },
  { id: 'meta-llama/llama-4-maverick-17b-128e-instruct', name: 'Llama 4 Maverick 17B', provider: 'groq', family: 'llama', pricing: { input: 2.0000000000000002e-7, output: 6e-7 }, contextWindow: 131072, maxOutput: 8192, modalities: { input: ["text","image"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: true } },
  { id: 'openai/gpt-oss-120b', name: 'GPT OSS 120B', provider: 'groq', family: 'gpt-oss', pricing: { input: 1.5e-7, output: 6e-7 }, contextWindow: 131072, maxOutput: 65536, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: true } },
  { id: 'openai/gpt-oss-20b', name: 'GPT OSS 20B', provider: 'groq', family: 'gpt-oss', pricing: { input: 7.5e-8, output: 3e-7 }, contextWindow: 131072, maxOutput: 65536, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: true } },
] as const satisfies readonly ModelDefinition[]
