// ──────────────────────────────────────────────────────────────
// ███████╗██╗   ██╗███╗   ██╗██╗  ██╗ █████╗ ██╗
// ██╔════╝██║   ██║████╗  ██║██║ ██╔╝██╔══██╗██║
// █████╗  ██║   ██║██╔██╗ ██║█████╔╝ ███████║██║
// ██╔══╝  ██║   ██║██║╚██╗██║██╔═██╗ ██╔══██║██║
// ██║     ╚██████╔╝██║ ╚████║██║  ██╗██║  ██║██║
// ╚═╝      ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝
//
// AUTO-GENERATED — DO NOT EDIT
// Source: https://models.dev
// Update: pnpm --filter=@funkai/models generate:models
// ──────────────────────────────────────────────────────────────

import type { ModelDefinition } from "../types.js";

export const HUGGINGFACE_MODELS = [
  {
    id: "zai-org/GLM-4.7-Flash",
    name: "GLM-4.7-Flash",
    provider: "huggingface",
    family: "glm",
    pricing: { input: 0, output: 0 },
    contextWindow: 200000,
    maxOutput: 128000,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "zai-org/GLM-4.7",
    name: "GLM-4.7",
    provider: "huggingface",
    family: "glm",
    pricing: { input: 6e-7, output: 0.0000022, cacheRead: 1.1e-7 },
    contextWindow: 204800,
    maxOutput: 131072,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "zai-org/GLM-5",
    name: "GLM-5",
    provider: "huggingface",
    family: "glm",
    pricing: {
      input: 0.000001,
      output: 0.0000032000000000000003,
      cacheRead: 2.0000000000000002e-7,
    },
    contextWindow: 202752,
    maxOutput: 131072,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "XiaomiMiMo/MiMo-V2-Flash",
    name: "MiMo-V2-Flash",
    provider: "huggingface",
    family: "mimo",
    pricing: { input: 1.0000000000000001e-7, output: 3e-7 },
    contextWindow: 262144,
    maxOutput: 4096,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "MiniMaxAI/MiniMax-M2.5",
    name: "MiniMax-M2.5",
    provider: "huggingface",
    family: "minimax",
    pricing: { input: 3e-7, output: 0.0000012, cacheRead: 3e-8 },
    contextWindow: 204800,
    maxOutput: 131072,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "MiniMaxAI/MiniMax-M2.1",
    name: "MiniMax-M2.1",
    provider: "huggingface",
    family: "minimax",
    pricing: { input: 3e-7, output: 0.0000012 },
    contextWindow: 204800,
    maxOutput: 131072,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "deepseek-ai/DeepSeek-R1-0528",
    name: "DeepSeek-R1-0528",
    provider: "huggingface",
    family: "deepseek-thinking",
    pricing: { input: 0.000003, output: 0.000005 },
    contextWindow: 163840,
    maxOutput: 163840,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "deepseek-ai/DeepSeek-V3.2",
    name: "DeepSeek-V3.2",
    provider: "huggingface",
    family: "deepseek",
    pricing: { input: 2.8e-7, output: 4.0000000000000003e-7 },
    contextWindow: 163840,
    maxOutput: 65536,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "moonshotai/Kimi-K2-Instruct",
    name: "Kimi-K2-Instruct",
    provider: "huggingface",
    family: "kimi",
    pricing: { input: 0.000001, output: 0.000003 },
    contextWindow: 131072,
    maxOutput: 16384,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "moonshotai/Kimi-K2-Instruct-0905",
    name: "Kimi-K2-Instruct-0905",
    provider: "huggingface",
    family: "kimi",
    pricing: { input: 0.000001, output: 0.000003 },
    contextWindow: 262144,
    maxOutput: 16384,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "moonshotai/Kimi-K2.5",
    name: "Kimi-K2.5",
    provider: "huggingface",
    family: "kimi",
    pricing: { input: 6e-7, output: 0.000003, cacheRead: 1.0000000000000001e-7 },
    contextWindow: 262144,
    maxOutput: 262144,
    modalities: { input: ["text", "image", "video"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "moonshotai/Kimi-K2-Thinking",
    name: "Kimi-K2-Thinking",
    provider: "huggingface",
    family: "kimi-thinking",
    pricing: { input: 6e-7, output: 0.0000025, cacheRead: 1.5e-7 },
    contextWindow: 262144,
    maxOutput: 262144,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "Qwen/Qwen3-Next-80B-A3B-Instruct",
    name: "Qwen3-Next-80B-A3B-Instruct",
    provider: "huggingface",
    family: "qwen",
    pricing: { input: 2.5e-7, output: 0.000001 },
    contextWindow: 262144,
    maxOutput: 66536,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "Qwen/Qwen3.5-397B-A17B",
    name: "Qwen3.5-397B-A17B",
    provider: "huggingface",
    family: "qwen",
    pricing: { input: 6e-7, output: 0.0000036000000000000003 },
    contextWindow: 262144,
    maxOutput: 32768,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "Qwen/Qwen3-235B-A22B-Thinking-2507",
    name: "Qwen3-235B-A22B-Thinking-2507",
    provider: "huggingface",
    family: "qwen",
    pricing: { input: 3e-7, output: 0.000003 },
    contextWindow: 262144,
    maxOutput: 131072,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "Qwen/Qwen3-Coder-Next",
    name: "Qwen3-Coder-Next",
    provider: "huggingface",
    family: "qwen",
    pricing: { input: 2.0000000000000002e-7, output: 0.0000015 },
    contextWindow: 262144,
    maxOutput: 65536,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "Qwen/Qwen3-Coder-480B-A35B-Instruct",
    name: "Qwen3-Coder-480B-A35B-Instruct",
    provider: "huggingface",
    family: "qwen",
    pricing: { input: 0.000002, output: 0.000002 },
    contextWindow: 262144,
    maxOutput: 66536,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "Qwen/Qwen3-Embedding-4B",
    name: "Qwen 3 Embedding 4B",
    provider: "huggingface",
    family: "qwen",
    pricing: { input: 1e-8, output: 0 },
    contextWindow: 32000,
    maxOutput: 2048,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: false, attachment: false, structuredOutput: false },
  },
  {
    id: "Qwen/Qwen3-Embedding-8B",
    name: "Qwen 3 Embedding 8B",
    provider: "huggingface",
    family: "qwen",
    pricing: { input: 1e-8, output: 0 },
    contextWindow: 32000,
    maxOutput: 4096,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: false, attachment: false, structuredOutput: false },
  },
  {
    id: "Qwen/Qwen3-Next-80B-A3B-Thinking",
    name: "Qwen3-Next-80B-A3B-Thinking",
    provider: "huggingface",
    family: "qwen",
    pricing: { input: 3e-7, output: 0.000002 },
    contextWindow: 262144,
    maxOutput: 131072,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
] as const satisfies readonly ModelDefinition[];
