// ──────────────────────────────────────────────────────────────
// ███████╗██╗   ██╗███╗   ██╗██╗  ██╗ █████╗ ██╗
// ██╔════╝██║   ██║████╗  ██║██║ ██╔╝██╔══██╗██║
// █████╗  ██║   ██║██╔██╗ ██║█████╔╝ ███████║██║
// ██╔══╝  ██║   ██║██║╚██╗██║██╔═██╗ ██╔══██║██║
// ██║     ╚██████╔╝██║ ╚████║██║  ██╗██║  ██║██║
// ╚═╝      ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝
//
// AUTO-GENERATED — DO NOT EDIT
// Source: https://models.dev
// Update: pnpm --filter=@funkai/models generate:models
// ──────────────────────────────────────────────────────────────

import type { ModelDefinition } from "../types.js";

export const MISTRAL_MODELS = [
  {
    id: "devstral-medium-2507",
    name: "Devstral Medium",
    provider: "mistral",
    family: "devstral",
    pricing: { input: 4.0000000000000003e-7, output: 0.000002 },
    contextWindow: 128000,
    maxOutput: 128000,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "labs-devstral-small-2512",
    name: "Devstral Small 2",
    provider: "mistral",
    family: "devstral",
    pricing: { input: 0, output: 0 },
    contextWindow: 256000,
    maxOutput: 256000,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "devstral-medium-latest",
    name: "Devstral 2 (latest)",
    provider: "mistral",
    family: "devstral",
    pricing: { input: 4.0000000000000003e-7, output: 0.000002 },
    contextWindow: 262144,
    maxOutput: 262144,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "open-mistral-7b",
    name: "Mistral 7B",
    provider: "mistral",
    family: "mistral",
    pricing: { input: 2.5e-7, output: 2.5e-7 },
    contextWindow: 8000,
    maxOutput: 8000,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "mistral-small-2506",
    name: "Mistral Small 3.2",
    provider: "mistral",
    family: "mistral-small",
    pricing: { input: 1.0000000000000001e-7, output: 3e-7 },
    contextWindow: 128000,
    maxOutput: 16384,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "mistral-medium-2505",
    name: "Mistral Medium 3",
    provider: "mistral",
    family: "mistral-medium",
    pricing: { input: 4.0000000000000003e-7, output: 0.000002 },
    contextWindow: 131072,
    maxOutput: 131072,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "codestral-latest",
    name: "Codestral (latest)",
    provider: "mistral",
    family: "codestral",
    pricing: { input: 3e-7, output: 9.000000000000001e-7 },
    contextWindow: 256000,
    maxOutput: 4096,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "ministral-8b-latest",
    name: "Ministral 8B (latest)",
    provider: "mistral",
    family: "ministral",
    pricing: { input: 1.0000000000000001e-7, output: 1.0000000000000001e-7 },
    contextWindow: 128000,
    maxOutput: 128000,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "magistral-small",
    name: "Magistral Small",
    provider: "mistral",
    family: "magistral-small",
    pricing: { input: 5e-7, output: 0.0000015 },
    contextWindow: 128000,
    maxOutput: 128000,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "mistral-large-2512",
    name: "Mistral Large 3",
    provider: "mistral",
    family: "mistral-large",
    pricing: { input: 5e-7, output: 0.0000015 },
    contextWindow: 262144,
    maxOutput: 262144,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "ministral-3b-latest",
    name: "Ministral 3B (latest)",
    provider: "mistral",
    family: "ministral",
    pricing: { input: 4e-8, output: 4e-8 },
    contextWindow: 128000,
    maxOutput: 128000,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "mistral-embed",
    name: "Mistral Embed",
    provider: "mistral",
    family: "mistral-embed",
    pricing: { input: 1.0000000000000001e-7, output: 0 },
    contextWindow: 8000,
    maxOutput: 3072,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: false, attachment: false, structuredOutput: false },
  },
  {
    id: "devstral-small-2505",
    name: "Devstral Small 2505",
    provider: "mistral",
    family: "devstral",
    pricing: { input: 1.0000000000000001e-7, output: 3e-7 },
    contextWindow: 128000,
    maxOutput: 128000,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "pixtral-12b",
    name: "Pixtral 12B",
    provider: "mistral",
    family: "pixtral",
    pricing: { input: 1.5e-7, output: 1.5e-7 },
    contextWindow: 128000,
    maxOutput: 128000,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "open-mixtral-8x7b",
    name: "Mixtral 8x7B",
    provider: "mistral",
    family: "mixtral",
    pricing: { input: 7e-7, output: 7e-7 },
    contextWindow: 32000,
    maxOutput: 32000,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "pixtral-large-latest",
    name: "Pixtral Large (latest)",
    provider: "mistral",
    family: "pixtral",
    pricing: { input: 0.000002, output: 0.000006 },
    contextWindow: 128000,
    maxOutput: 128000,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "mistral-nemo",
    name: "Mistral Nemo",
    provider: "mistral",
    family: "mistral-nemo",
    pricing: { input: 1.5e-7, output: 1.5e-7 },
    contextWindow: 128000,
    maxOutput: 128000,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "devstral-2512",
    name: "Devstral 2",
    provider: "mistral",
    family: "devstral",
    pricing: { input: 4.0000000000000003e-7, output: 0.000002 },
    contextWindow: 262144,
    maxOutput: 262144,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "mistral-large-latest",
    name: "Mistral Large (latest)",
    provider: "mistral",
    family: "mistral-large",
    pricing: { input: 5e-7, output: 0.0000015 },
    contextWindow: 262144,
    maxOutput: 262144,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "mistral-medium-2508",
    name: "Mistral Medium 3.1",
    provider: "mistral",
    family: "mistral-medium",
    pricing: { input: 4.0000000000000003e-7, output: 0.000002 },
    contextWindow: 262144,
    maxOutput: 262144,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false },
  },
  {
    id: "mistral-large-2411",
    name: "Mistral Large 2.1",
    provider: "mistral",
    family: "mistral-large",
    pricing: { input: 0.000002, output: 0.000006 },
    contextWindow: 131072,
    maxOutput: 16384,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "mistral-small-latest",
    name: "Mistral Small (latest)",
    provider: "mistral",
    family: "mistral-small",
    pricing: { input: 1.0000000000000001e-7, output: 3e-7 },
    contextWindow: 128000,
    maxOutput: 16384,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "open-mixtral-8x22b",
    name: "Mixtral 8x22B",
    provider: "mistral",
    family: "mixtral",
    pricing: { input: 0.000002, output: 0.000006 },
    contextWindow: 64000,
    maxOutput: 64000,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "mistral-medium-latest",
    name: "Mistral Medium (latest)",
    provider: "mistral",
    family: "mistral-medium",
    pricing: { input: 4.0000000000000003e-7, output: 0.000002 },
    contextWindow: 128000,
    maxOutput: 16384,
    modalities: { input: ["text", "image"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "devstral-small-2507",
    name: "Devstral Small",
    provider: "mistral",
    family: "devstral",
    pricing: { input: 1.0000000000000001e-7, output: 3e-7 },
    contextWindow: 128000,
    maxOutput: 128000,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false },
  },
  {
    id: "magistral-medium-latest",
    name: "Magistral Medium (latest)",
    provider: "mistral",
    family: "magistral-medium",
    pricing: { input: 0.000002, output: 0.000005 },
    contextWindow: 128000,
    maxOutput: 16384,
    modalities: { input: ["text"], output: ["text"] },
    capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false },
  },
] as const satisfies readonly ModelDefinition[];
