// ──────────────────────────────────────────────────────────────
// ███████╗██╗   ██╗███╗   ██╗██╗  ██╗ █████╗ ██╗
// ██╔════╝██║   ██║████╗  ██║██║ ██╔╝██╔══██╗██║
// █████╗  ██║   ██║██╔██╗ ██║█████╔╝ ███████║██║
// ██╔══╝  ██║   ██║██║╚██╗██║██╔═██╗ ██╔══██║██║
// ██║     ╚██████╔╝██║ ╚████║██║  ██╗██║  ██║██║
// ╚═╝      ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝
//
// AUTO-GENERATED — DO NOT EDIT
// Source: https://models.dev
// Update: pnpm --filter=@funkai/models generate:models
// ──────────────────────────────────────────────────────────────

import type { ModelDefinition } from '../types.js'

export const XAI_MODELS: readonly ModelDefinition[] = [
  { id: 'grok-2-1212', name: 'Grok 2 (1212)', provider: 'xai', family: 'grok', pricing: { input: 0.000002, output: 0.00001, cacheRead: 0.000002 }, contextWindow: 131072, maxOutput: 8192, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'grok-4.20-beta-latest-non-reasoning', name: 'Grok 4.20 Beta (Non-Reasoning)', provider: 'xai', family: 'grok', pricing: { input: 0.000002, output: 0.000006, cacheRead: 2.0000000000000002e-7 }, contextWindow: 2000000, maxOutput: 30000, modalities: { input: ["text","image"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false } },
  { id: 'grok-2', name: 'Grok 2', provider: 'xai', family: 'grok', pricing: { input: 0.000002, output: 0.00001, cacheRead: 0.000002 }, contextWindow: 131072, maxOutput: 8192, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'grok-3-fast-latest', name: 'Grok 3 Fast Latest', provider: 'xai', family: 'grok', pricing: { input: 0.000005, output: 0.000025, cacheRead: 0.00000125 }, contextWindow: 131072, maxOutput: 8192, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'grok-2-vision', name: 'Grok 2 Vision', provider: 'xai', family: 'grok', pricing: { input: 0.000002, output: 0.00001, cacheRead: 0.000002 }, contextWindow: 8192, maxOutput: 4096, modalities: { input: ["text","image"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false } },
  { id: 'grok-3', name: 'Grok 3', provider: 'xai', family: 'grok', pricing: { input: 0.000003, output: 0.000015, cacheRead: 7.5e-7 }, contextWindow: 131072, maxOutput: 8192, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'grok-code-fast-1', name: 'Grok Code Fast 1', provider: 'xai', family: 'grok', pricing: { input: 2.0000000000000002e-7, output: 0.0000015, cacheRead: 2e-8 }, contextWindow: 256000, maxOutput: 10000, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'grok-2-vision-1212', name: 'Grok 2 Vision (1212)', provider: 'xai', family: 'grok', pricing: { input: 0.000002, output: 0.00001, cacheRead: 0.000002 }, contextWindow: 8192, maxOutput: 4096, modalities: { input: ["text","image"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false } },
  { id: 'grok-4-1-fast-non-reasoning', name: 'Grok 4.1 Fast (Non-Reasoning)', provider: 'xai', family: 'grok', pricing: { input: 2.0000000000000002e-7, output: 5e-7, cacheRead: 5.0000000000000004e-8 }, contextWindow: 2000000, maxOutput: 30000, modalities: { input: ["text","image"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false } },
  { id: 'grok-beta', name: 'Grok Beta', provider: 'xai', family: 'grok-beta', pricing: { input: 0.000005, output: 0.000015, cacheRead: 0.000005 }, contextWindow: 131072, maxOutput: 4096, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'grok-3-mini-fast', name: 'Grok 3 Mini Fast', provider: 'xai', family: 'grok', pricing: { input: 6e-7, output: 0.000004, cacheRead: 1.5e-7 }, contextWindow: 131072, maxOutput: 8192, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'grok-4-fast', name: 'Grok 4 Fast', provider: 'xai', family: 'grok', pricing: { input: 2.0000000000000002e-7, output: 5e-7, cacheRead: 5.0000000000000004e-8 }, contextWindow: 2000000, maxOutput: 30000, modalities: { input: ["text","image"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false } },
  { id: 'grok-4', name: 'Grok 4', provider: 'xai', family: 'grok', pricing: { input: 0.000003, output: 0.000015, cacheRead: 7.5e-7 }, contextWindow: 256000, maxOutput: 64000, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'grok-4.20-multi-agent-beta-latest', name: 'Grok 4.20 Multi-Agent Beta', provider: 'xai', family: 'grok', pricing: { input: 0.000002, output: 0.000006, cacheRead: 2.0000000000000002e-7 }, contextWindow: 2000000, maxOutput: 30000, modalities: { input: ["text","image"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false } },
  { id: 'grok-3-latest', name: 'Grok 3 Latest', provider: 'xai', family: 'grok', pricing: { input: 0.000003, output: 0.000015, cacheRead: 7.5e-7 }, contextWindow: 131072, maxOutput: 8192, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'grok-4-1-fast', name: 'Grok 4.1 Fast', provider: 'xai', family: 'grok', pricing: { input: 2.0000000000000002e-7, output: 5e-7, cacheRead: 5.0000000000000004e-8 }, contextWindow: 2000000, maxOutput: 30000, modalities: { input: ["text","image"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false } },
  { id: 'grok-2-vision-latest', name: 'Grok 2 Vision Latest', provider: 'xai', family: 'grok', pricing: { input: 0.000002, output: 0.00001, cacheRead: 0.000002 }, contextWindow: 8192, maxOutput: 4096, modalities: { input: ["text","image"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false } },
  { id: 'grok-3-mini-latest', name: 'Grok 3 Mini Latest', provider: 'xai', family: 'grok', pricing: { input: 3e-7, output: 5e-7, cacheRead: 7.5e-8 }, contextWindow: 131072, maxOutput: 8192, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'grok-3-mini', name: 'Grok 3 Mini', provider: 'xai', family: 'grok', pricing: { input: 3e-7, output: 5e-7, cacheRead: 7.5e-8 }, contextWindow: 131072, maxOutput: 8192, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'grok-3-mini-fast-latest', name: 'Grok 3 Mini Fast Latest', provider: 'xai', family: 'grok', pricing: { input: 6e-7, output: 0.000004, cacheRead: 1.5e-7 }, contextWindow: 131072, maxOutput: 8192, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'grok-2-latest', name: 'Grok 2 Latest', provider: 'xai', family: 'grok', pricing: { input: 0.000002, output: 0.00001, cacheRead: 0.000002 }, contextWindow: 131072, maxOutput: 8192, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'grok-4-fast-non-reasoning', name: 'Grok 4 Fast (Non-Reasoning)', provider: 'xai', family: 'grok', pricing: { input: 2.0000000000000002e-7, output: 5e-7, cacheRead: 5.0000000000000004e-8 }, contextWindow: 2000000, maxOutput: 30000, modalities: { input: ["text","image"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false } },
  { id: 'grok-vision-beta', name: 'Grok Vision Beta', provider: 'xai', family: 'grok-vision', pricing: { input: 0.000005, output: 0.000015, cacheRead: 0.000005 }, contextWindow: 8192, maxOutput: 4096, modalities: { input: ["text","image"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: true, structuredOutput: false } },
  { id: 'grok-3-fast', name: 'Grok 3 Fast', provider: 'xai', family: 'grok', pricing: { input: 0.000005, output: 0.000025, cacheRead: 0.00000125 }, contextWindow: 131072, maxOutput: 8192, modalities: { input: ["text"], output: ["text"] }, capabilities: { reasoning: false, toolCall: true, attachment: false, structuredOutput: false } },
  { id: 'grok-4.20-beta-latest-reasoning', name: 'Grok 4.20 Beta (Reasoning)', provider: 'xai', family: 'grok', pricing: { input: 0.000002, output: 0.000006, cacheRead: 2.0000000000000002e-7 }, contextWindow: 2000000, maxOutput: 30000, modalities: { input: ["text","image"], output: ["text"] }, capabilities: { reasoning: true, toolCall: true, attachment: true, structuredOutput: false } },
] as const
